### ISSUE TITLE
iadd_cout isn't properly defined on x86

### ISSUE THREAD

**Issue by bnjbvr** [CraneStation/cranelift#1009]
cc @ryzokuken @sunfishcode 

With #957, I get the same register allocation mentioned several times in several issues, including probably #1002 and in the PR https://github.com/CraneStation/cranelift/pull/993#issuecomment-529037556 . This is because all these tests involve iadd, which gets legalized into an iadd_cout. On x86, iadd_cout uses the "rr" recipe, but it's incorrect in doing so: the rr recipe is wired for one output registers, not two, so register allocation doesn't even bother filling in the second output register.

Instead, there should be different recipes with different output operands.

Bonus points if we could add some checks in the meta-build that all of the results are somehow handled: the number of output SSA values in the instruction must be equal to the number of output operands in the recipe. (Claim to be confirmed, but this seems sane.)

**Comment by ryzokuken** [comment]
I guess this qualifies as a bug in my PR that introduced the opcode for iadd_cout and isub_bout. Will fix.

**Comment by ryzokuken** [comment]
I made a PR (#1014) for fixing the current `iadd_cout` and `isub_bout` situation, but moving forwards, we should implement what @bnjbvr mentioned.

> Bonus points if we could add some checks in the meta-build that all of the results are somehow handled: the number of output SSA values in the instruction must be equal to the number of output operands in the recipe. (Claim to be confirmed, but this seems sane.)

I guess the typestate pattern could come in handy? (http://cliffle.com/blog/rust-typestate/)
