### ISSUE TITLE
cranelift-wasm::FuncTranslator::{translate, translate_from_reader} signature change

### ISSUE THREAD

**Issue by pchickey** [CraneStation/cranelift#1021]
In #671, the signature of `FuncTranslator::translate` was changed from taking a `&mut ir::Function` and returning `WasmResult<()>` to taking a `ir::Function` and returning `WasmResult<ir::Function>`:

https://github.com/CraneStation/cranelift/commit/4cd2c76c65cf71990d4ec9b9679c4755fafa75ed#diff-3a8aa8abcffafb563225730ebca50b04L60

The Function given as an argument is required to be empty, and only provides its `name` and `signature` to the builder inside `FuncTranslator`:

https://github.com/CraneStation/cranelift/commit/4cd2c76c65cf71990d4ec9b9679c4755fafa75ed#diff-3a8aa8abcffafb563225730ebca50b04R78

This was an understandable restriction before #671, but now that the function is no longer passed mutably, it makes more sense to just pass in the `name: ExternalName` and `signature: ir::Signature` as arguments to `translate` rather than passing an entire `ir::Function`.

The change itself is trivial, but it is a breaking API change, so I'd like to seek feedback before making a PR.

**Comment by abrown** [comment]
Seems like this depends on the outcome of #1018? If the API is changed back to the way it was then this might not be applicable.

**Comment by bnjbvr** [comment]
Closing since #671 has been reverted. Thanks for opening an issue though! It would have been a welcome improvement.
