### ISSUE TITLE
Make ConstantData the mechanism for interacting with constant values

### ISSUE THREAD

**Issue by abrown** [CraneStation/cranelift#1027]
As mentioned in https://github.com/CraneStation/cranelift/pull/974#discussion_r324291764 and https://github.com/CraneStation/cranelift/pull/974#discussion_r324293444, `Uimm128` is used for parsing and writing constant values from and to CLIF. If the constant pool is needed for types other than 128-bit vectors, then a more flexible type is needed. `ConstantData` can become this but needs to:
 - become a real type, not a type alias
 - acquire implementations for `FromStr` and `Display` 
 - replace `Uimm128` in the various places conversions are currently made (e.g. `parser.rs`, `write.rs`)

I wonder if in the end this makes `Uimm128` superfluous and it can be removed.

**Comment by bnjbvr** [comment]
Thanks for opening an issue! Sounds great to me.
