### ISSUE TITLE
Name opcodes statically

### ISSUE THREAD

**Issue by abrown** [CraneStation/cranelift#1051]
As @sstangl mentions in https://github.com/CraneStation/cranelift/pull/1013#discussion_r326379569, it would be nicer if 

```rec_vconst_opt.nonrex().opcodes(vec![0x66, 0x0f, 0x74]); // PCMPEQB from SSE2```

were actually more like

```rec_vconst_opt.nonrex().opcodes(PCMPEQB);```.

This would reduce the opportunity for programmer error and duplication and could be implemented by placing all of the opcodes in a separate `opcodes.rs` file referenced by `encodings.rs`. I do not think we need to use `lazy_static` in this case (unlike we discussed in #955) because we could write:
```
static PCMPEQB: [u8; 3] = [0x66, 0x0f, 0x74]; // or...
static PCMPEQB: &'static [u8] = &[0x66, 0x0f, 0x74];
```
And modify `Template::opcodes` to receive more than just a `Vec<u8`.

**Comment by bnjbvr** [comment]
I like this idea; RISCV has something like this with small helper functions.

**Comment by sstangl** [comment]
I'll just take this to spare others from the tedium.

**Comment by sstangl** [comment]
Almost done. 104 left.
