### ISSUE TITLE
will rustc have a cranelift backend ? 

### ISSUE THREAD

**Issue by lithic** [CraneStation/cranelift#1056]

**Comment by bjorn3** [comment]
I am working on one: https://github.com/bjorn3/rustc_codegen_cranelift/

**Comment by sstangl** [comment]
It's not the focus at the moment (wasm compilation is), but Cranelift was designed with Rust in mind too.

**Comment by nbp** [comment]
I think @sunfishcode and @tschneidereit might have a more nuanced answer about the current goals of Cranelift.
