### ISSUE TITLE
Allow switching between EBBs before they are filled

### ISSUE THREAD

**Issue by jyn514** [CraneStation/cranelift#1057]
Copied from IRC:

Is there a way to switch to another ebb and then switch back to the current one? I'm getting 'you have to fill your block before switching' when I try. My use case is I want to generate a switch statement without knowing all the jump EBBs ahead of time. I'm generating each ebb, which calls `switch.set_entry` as it gets translated, and then at the end switching back to the original block and calling `switch.emit`. Looking at https://docs.rs/cranelift-frontend/0.43.1/src/cranelift_frontend/frontend.rs.html#256-274 there doesn't seem to be any intrinsic reason to not switch blocks, it's just a debug assertion.

I think this hasn't popped up before because Rust's `match` statements have very clear entry points and exit points, unlike C (how many EBBs are in [this code](https://godbolt.org/z/5jBPZ7)?) and `cranelift-wasm` [uses `br_table` directly](https://github.com/CraneStation/cranelift/blob/master/cranelift-wasm/src/code_translator.rs#L267) instead of a `Switch`.

**Comment by jyn514** [comment]
I have a prototype using this locally (I used `--release` to disable debug assertions) and there doesn't seem to be an issue with the verifier or anything like that.

**Comment by jyn514** [comment]
If this was intended as a debugging aid, maybe there could be a setting to enable/disable it in `settings::builder`? That way you get the checks by default, but can still turn them off if you know what you're doing.

**Comment by nbp** [comment]
For your information, we are going to drop EBB's support soon.

**Comment by jyn514** [comment]
@nbp would that affect whether users of `FunctionBuilder` can switch between blocks without filling the Basic Block?

**Comment by nbp** [comment]
I presume yes, as we have restriction on the terminator of the basic blocks. On the other hand, you can always end you basic block with a jump to a block which is allocated right after it, and jump to a different block to fill it.  The problem then would be to reorder the block later on to ensure that we can use `fallthrough` instructions instead of `jump`.

**Comment by jyn514** [comment]
I don't think this is worth the effort to change, I worked around it in some of my own code.
