### ISSUE TITLE
Codegen-meta's Isa::all() signature is too limiting

### ISSUE THREAD

**Issue by ckaran** [CraneStation/cranelift#1082]
I just read the code at https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/meta/src/isa/mod.rs for `Isa::all()`; it has the following signature:

```rust
pub fn all() -> [Isa; 4];
```

That is **really** limiting, it should be

```rust
pub fn all() -> Vec<Isa>;
```

or 

```rust
pub fn all() -> &Vec<Isa>;
```

so that when cranelift becomes **the** backend for everything rust we can just keep adding in new ISAs :smile:

**Comment by bjorn3** [comment]
I think it should be `&[Isa]`.

**Comment by ckaran** [comment]
@bjorn3 You're right, that's better.

**Comment by frazar** [comment]
Shouldn't this be closed?

**Comment by bnjbvr** [comment]
Yep thanks.
