### ISSUE TITLE
[bugpoint] merge ebbs

### ISSUE THREAD

**Issue by bjorn3** [CraneStation/cranelift#1124]
For example:

```
    some_insts
    jump ebb1

ebb1:
    more_insts
```

can be turned into

```
    some_insts
    more_insts
```

**Comment by nbp** [comment]
Do not forget to disable this code when using basic blocks, as this might not be true if `some_isnts` is a conditional branch.

**Comment by bjorn3** [comment]
Bugpoint generates a lot of invalid ir, but it checks everything using the verifier to discard those mutations which are invalid. I think it should to check for a conditional branch when using basic blocks anyway, to reduce the amount of wasted work.
