### ISSUE TITLE
wasm translation regression in wasm_linpack_float

### ISSUE THREAD

**Issue by bnjbvr** [CraneStation/cranelift#1132]
[wasm_linpack_float](https://github.com/lars-t-hansen/embenchen/blob/master/asm_v_wasm/wasm_linpack_float.c.wasm) doesn't validate anymore when compiled when running `cargo run wasm --target x86_64 -d /tmp/wasm_linpack_float.c.wasm`. This impacts more test cases, since the wasm test suite in Spidermonkey now passes fewer tests.

There seems to be a jump to an incorrect block.

Bisection shows the following:

```
ee6fe21f924179466dd10c7b5b1e3c8e2422a7fa is the first bad commit
commit ee6fe21f924179466dd10c7b5b1e3c8e2422a7fa
Author: Nick Fitzgerald </snip>
Date:   Wed Oct 2 16:28:46 2019 -0700

    cranelift-wasm: Jump to the destination block at end of consequent
```

Will try to make a reduced test case.

@fitzgen Could you have a look, please? Thanks!

**Comment by fitzgen** [comment]
@bnjbvr thanks for the heads up. Did you end up creating a reduced test case? Are there instructions somewhere for how I can get those benchmarks up and running somewhere?

**Comment by fitzgen** [comment]
nvm, I've got it working locally.

**Comment by fitzgen** [comment]
Reduced test case:

```wat
(module
  (type (;0;) (func (param i32) (result i32)))
  (import "env" "table" (table (;0;) 12 12 funcref))
  (func (;0;) (type 0) (param i32) (result i32)
    i32.const 0
    if  ;; label = @1
      i32.const 0
      if  ;; label = @2
        nop
      else
        unreachable
      end
      unreachable
    end
    unreachable)
  (elem (;0;) (i32.const 1)))
```
