### ISSUE TITLE
Remove TODO about the unused Immediate struct in legalization patterns

### ISSUE THREAD

**Issue by stefson** [CraneStation/cranelift#1150]
It just happend that I got a warning spawned on the latest git checkout: 

```
warning: variant is never constructed: `UInt8`
   --> cranelift-codegen/meta/src/cdsl/instructions.rs:456:5
    |
456 |     UInt8(u8),
    |     ^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: variant is never constructed: `UInt128`
   --> cranelift-codegen/meta/src/cdsl/instructions.rs:457:5
    |
457 |     UInt128(u128),
    |     ^^^^^^^^^^^^^

```

this is on x86_64-pc-linux-gnu and with rustc-1.38.0

**Comment by bnjbvr** [comment]
Indeed, thanks for opening an issue! I think @abrown had plans to use this, and I swear I saw usage of this somewhere; maybe it was in an open PR?

**Comment by abrown** [comment]
I mean I added it because I knew I should be using it but I probably haven't got there yet. Should we disable the `dead_code` warning there until we do?

**Comment by bnjbvr** [comment]
Yes, it makes sense to temporarily allow dead code. (Another possibility is be to find a legalization that needs an immediate and was put in a custom legalization function, and replace it, but oh well :))

**Comment by bnjbvr** [comment]
Morphing the issue, since there's a fix for the dead code warning.

**Comment by stefson** [comment]
The warning is gone now, shall I close this?

**Comment by bnjbvr** [comment]
No, let's keep it for a different purpose, that is removing the TODO that's next to the Immediate structure now. Thanks for checking :)
