### ISSUE TITLE
Build fails with verifier issues

### ISSUE THREAD

**Issue by abrown** [CraneStation/cranelift#1152]
On master, build is failing during `cargo test` with:
```
AIL filetests\regalloc\solver-fixedconflict-var-3.clif: function u0:0(i32, i32, i32, i64 vmctx) -> i64 uext system_v {
ebb0(v0: i32, v1: i32, v2: i32, v3: i64):
    v5 = iconst.i32 -8
    v114 = iconst.i32 0
    v16 = iconst.i32 -8
    v17 = popcnt v16
    v192 = ifcmp_imm v17, -1
    brif eq v192, ebb12
    trap user0
;   ^~~~~~~~~~
; error: inst6: post-branch instruction not fallthrough or jump
...
```
Looks like it starts after merging #1127

**Comment by abrown** [comment]
cc @iximeow, @bnjbvr, @sunfishcode

**Comment by sunfishcode** [comment]
Could someone try adjusting the testcase in the manner of https://github.com/CraneStation/cranelift/commit/bf2bf6b041458beae320853fa8f46c10d4dfe5ca#diff-b87c8ccc2de2ec5b1d1fb3ae8b9f3a82 ?

**Comment by sstangl** [comment]
Nicolas turned on the basic-block feature by default, and I guess this test wasn't updated. I'll take it.

**Comment by iximeow** [comment]
oop, I'd been looking at this from the irc conversation, didn't see your comment. Either should do.
