### ISSUE TITLE
Cranelift vs SpiderMonkey compilation speed comparison

### ISSUE THREAD

**Issue by kripken** [CraneStation/cranelift#239]
Data in https://docs.google.com/spreadsheets/d/1G7AgxK2J0Tz74U7QgcMG7tJld0_q5N2U-LvUq9SBk84/edit?usp=sharing

There are three charts there each in their own tab.

The data shows 4 wasm files, TWO, THREE, FOUR, FIVE, on each of which the ratio of instructions (as measured by `perf stat` - more robust than measuring time) was Cretonne two/three/four/five times slower than SpiderMonkey. This is measured by
```
mozjs --no-threads --no-wasm-baseline input.js
cretonne/target/release/cton-util wasm --set=enable_verifier=0 --set=is_64bit '--isa=intel haswell' input.wasm
```
The wasms were reduced by binaryen wasm-reduce, shrinking them while the ratio stays in the right range. Original input was just a large random fuzz testcase, nothing special - this isn't a corner case, it's typical for what the fuzzer generates.

Note that SpiderMonkey is loading a full VM + JS which loads and compiles the wasm, while Cretonne is just compiling the wasm, so this is not entirely apples to apples, so there is a column for SpiderMonkey which removes the work it takes just to load the VM + JS.

Results in the three charts each show bunches of 4 colors, which are TWO, THREE, FOUR and FIVE in order. That is, it shows the results on wasms of increasing size. In more detail, here is what each of the three charts show, in order:

 * The # of instructions SpiderMonkey issues on the left; in the middle without the VM + JS overhead, and on the right Cretonne. Both compilers scale mostly linearly.
 * A breakdown of the main Cretonne timing numbers from `-T`: compilation passes, regalloc, translate module, translate function, ra coloring. All phases seem to scale linearly.
 * How many instructions are issued divided by the wasm size. In both VMs the ratio is essentially a constant.

Overall it seems Cretonne does significantly more work than SpiderMonkey, if these calculations are correct?

**Comment by stoklund** [comment]
Thanks!

To be clear, we haven't spent any effort towards optimizing Cretonne's compile time yet.

**Comment by sunfishcode** [comment]
Also worth noting is that when built as part of cton-util, it enables assertions and disables some optimization, [here](https://github.com/Cretonne/cretonne/blob/master/Cargo.toml#L31).

**Comment by sunfishcode** [comment]
Closing this; we can continue to track compile time with individual issues tagged with the FA-compile-time label.
