### ISSUE TITLE
Reload: Elide copy instructions

### ISSUE THREAD

**Issue by stoklund** [CraneStation/cranelift#245]
Copy instructions are inserted by two regalloc passes before the reload pass:

1. The coalescer can insert copies before branches to separate virtual registers that would conflict.
2. The spiller can insert copies before two-address instructions, and to deal with other tricky constraints.

The reload pass should handle these copy instructions better when one or both values have been spilled.

```
v10 = copy v5
```

Currently becomes:

```
v50 = fill v5
v10 = copy v50
```

or

```
v50 = copy v5
v10 = spill v50
```

These copies are not necessary. If the reload pass recognized `copy` instructions, we could do better:

```
v10 = fill v5
```

or

```
v10 = spill v5
```

In the case where both values were spilled, we need a stack-stack copy:

```
v50 = fill v5
v10 = spill v50
```

**Comment by mlea13** [comment]
I've started working on a fix for this, but I just had one question about testing this change. I took a look at the test files under cranelift/filetests/regalloc/ but I was wondering if there was some documentation on the test runner or how to write the these types of tests.

**Comment by sunfishcode** [comment]
The main testing documentation is [here](https://cranelift.readthedocs.io/en/latest/testing.html), with a [paragraph about regalloc tests](https://cranelift.readthedocs.io/en/latest/testing.html#test-regalloc) specifically. For anything that doesn't cover, feel free to ask questions here and we'll do our best to answer them and/or update the docs :-).

**Comment by mlea13** [comment]
Thanks for the pointers, they were very helpful!

**Comment by mlea13** [comment]
Hey, I just had another quick question about replacing instructions. After playing around with the regalloc passes a bit, I realized that when I replace a copy instruction with a fill or spill instruction I also need to update the instruction encoding. The reload pass seems to use the` EncCursor` to handle this for the insert instruction case. Would it make sense to try to extend the `EncCursor` to have similar replace functionality? The `ReplaceBuilder` seems to be set up slightly differently than the `InsertBuilder` which uses an `InstInserter`.

**Comment by sunfishcode** [comment]
That sounds reasonable to me. Replacing is conceptually the same as inserting new instructions and deleting the old ones, except for directly reusing their indices.

**Comment by mlea13** [comment]
After looking at the code a bit more, I did not see a trivial way to update the EncCur to handle the encoding for the replace case. I ended up just do that directly in the reload pass. LMKWYT.
