### ISSUE TITLE
Reload: Reuse spilled values in registers

### ISSUE THREAD

**Issue by stoklund** [CraneStation/cranelift#246]
The reload pass should reuse spilled values that are known to be available in a register.

Example:

```
v3 = iadd v1, v2
v4= isub v1, v2
```

If `v1` is on the stack, reload currently generates:

```
v10 = fill v1
v3 = iadd v10, v2
v11 = fill v1
v4= isub v11, v2
```

We should reuse the `v10` value instead:

```
v10 = fill v2
v3 = iadd v10, v2
v4= isub v10, v2
```

This increases register pressure, so the reload pass will need to track the number of registers used the same way the spilling pass does it.

This optimization also applies immediately after a spill:

```
v1 = iconst.i32 42
v3 = iadd v1, v2
```

becomes (with `v1` spilled):

```
v10 = iconst.i32 42
v1 = spill v10
v11 = fill v1
v3 = iadd v11, v2
```

It is much better to reuse the register value `v10`:

```
v10 = iconst.i32 42
v1 = spill v10
v3 = iadd v10, v2
```

## Replacement strategy

The reload pass can be taught to keep track of multiple stack values that are also available in a register, but in order to control register pressure, some of these values need to be dropped eventually. The optimal replacement strategy is furthest-next-use — when we're using too many values, drop the register value whose next use is the furthest away.

The furthest-next-use strategy is possible to implement in a single scan over an EBB, but it requires some tricky bookkeeping. An LRU replacement strategy is simpler to implement, so it might be a better starting point.

## Scope

Initially, register values can be reused within an EBB. This is the easiest to implement. It is harder to reuse values across EBBs, in particular when dealing with EBBs with multiple predecessors.

**Comment by bjorn3** [comment]
Fixed by https://github.com/CraneStation/cranelift/pull/906 right?

**Comment by bnjbvr** [comment]
Good question: #906 implements a workaround that isn't integrated as part of register allocation as this issue proposed, but maybe that will eventually the final state, even after the regalloc re-work.

@lars-t-hansen @julian-seward1, what do you think? (In any case, issues are cheap so we can close this one and open another one later, if we wanted to take a different approach.)

**Comment by lars-t-hansen** [comment]
I think #906 fixed this as well as we can, for the time being, and anything that is much better than that is going to be part of a larger regalloc rewrite.  Let's close and reopen if/when we need to.
