### ISSUE TITLE
Serde serialization for Cranelift IR

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#261]
Cretonne IR is conceptually pretty simple: A Function contains signatures, stack slots, and other declarations, and then a list of basic blocks. A basic block has parameters and a list of instructions, and an instruction has an opcode, fields, and operands. It would be useful to be able to serialize to various formats that Serde supports, so we can build more options for working with and displaying Cretonne IR. However, it's awkward to use serde_derive directly, because Cretonne represents all of these conceptually simple things with specialized data structures.

We can solve this by creating an alternate set of data structures for holding Cretonne IR. A simple Function might use a `Vec<BasicBlock>` for holding basic blocks, and basic blocks might use `Vec<Instruction>` for their instructions, and then a translation between this alternate form and the main Cretonne IR data structures. This alternate form could then use `#[derive(Serialize, Deserialize)]` and Serde to serialize to a variety of formats.

**Comment by bjorn3** [comment]
[cnraleift-serde](https://github.com/CraneStation/cranelift/tree/d5c34954d9ea94732a1711542c2e42790870adb0/cranelift-serde) exists now.

**Comment by bnjbvr** [comment]
Thanks, indeed. Closing now!
