### ISSUE TITLE
It's not possible to identify different types of verifier errors without parsing the error message

### ISSUE THREAD

**Issue by dignissimus** [CraneStation/cranelift#284]

**Comment by sunfishcode** [comment]
Can you say more about what you're doing with verifier errors? I'd like to understand the expected use cases here better, before starting to design something to address them.

**Comment by sunfishcode** [comment]
Verifier errors essentially indicate a problem in wherever the IR came from, so we don't envision it being useful to making it easy to identify different types of errors. However, if you have use cases which would need this capability, please feel free to open this issue!
