### ISSUE TITLE
JIT Tutorial Milestone

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#289]
It would be very useful to have a tutorial showing how to use Cretonne as a JIT. I've created https://github.com/Cretonne/cretonne/milestone/1 to track progress on this milestone.

The goal is to not just build the tutorial, but also address some of Cretonne's incomplete and rough areas, as well as write up more introductory documentation, to simplify and enhance the tutorial. So, I'm interested in hearing from anyone who has looked at using Cretonne as a JIT. What was difficult? What was confusing? What would you like to see changed? What needed better documentation?

To start things off, wrangling relocations manually is tedious and tricky, so we'll need https://github.com/Cretonne/cretonne/issues/288 and probably some follow-ups to provide a convenient interface that takes care of bookkeeping, patching, and managing memory automatically.

Please feel free to file new issues, or suggest existing ones, that would be good to add to this milestone. Or just add comments to the issue here with any comments, questions, etc.

**Comment by sunfishcode** [comment]
Yeah, I started some basic tutorial content in README.md to accompany the code, but I got distracted by other projects temporarily. I am planning to finish that up and advertise it more broadly, hopefully in the next few weeks.

**Comment by sunfishcode** [comment]
As an update, the tutorial in the README.md is now basically finished, in the sense that it covers all the basics, though of course there will always be opportunities to explain things more or go into more detail.

**Comment by BurntSushi** [comment]
@sunfishcode Thank you!

**Comment by loic-sharma** [comment]
I agree with @BurntSushi, the demo is hard to find. What would you think of placing a link on the README next to the documentation link? Something like:

> For more information, see the documentation. For a basic example, see the demo.

**Comment by sunfishcode** [comment]
@loic-sharma Thanks for the suggestion! I've now added such a link [here](https://github.com/CraneStation/cranelift/#cranelift-code-generator).

**Comment by sunfishcode** [comment]
The last remaining issue here is now fixed! I think we can declare this milestone done!

The tutorial is in the README, with accompanying code in the repo here:

https://github.com/sunfishcode/simplejit-demo 

There's obvously room for more documentation, streamlining common use cases, and so on, so please file issues to report things that we can improve!
