### ISSUE TITLE
Verifier

### ISSUE THREAD

**Issue by stoklund** [CraneStation/cranelift#3]
Cretonne needs an IR verifier.

The verifier can be run before and after different passes. It checks those IR invariants that are not enforced by the type system.

Instruction integrity:
- The instruction format must match the opcode.
- All result values must be created for multi-valued instructions.
- Instructions with no results must have a `VOID` `first_type()`.
- All referenced entities must exist. (Values, EBBs, stack slots, ...)

EBB integrity:
- All instructions reached from the `ebb_insts` iterator must belong to the EBB as reported by `inst_ebb()`.
- Should we detect loops in the `ebb_insts` iterator? The current linked list representation could theoretically do it.
- Every EBB must end in a terminator instruction, and no other instruction can be a terminator.
- Every value in the `ebb_args` iterator belongs to the EBB as reported by `value_ebb`.

SSA form. All values used by an instruction must:
- Be defined by an instruction that exists and that is inserted in an EBB, or be an argument of an existing EBB.
- Dominate the instruction. This check should probably be skipped for EBBs that can't be reached from the entry.

Control flow graph and dominator tree integrity.
- All predecessors in the CFG must be branches to the EBB.
- All branches to an EBB must be present in the CFG.
- A recomputed dominator tree is identical to the existing one.

Type checking:
- Verify all input and output values against the opcode's type constraints. For polymorphic opcodes, determine the controlling type variable first.
- Branches and jumps must pass arguments to destination EBBs that match the expected types excatly. The number of arguments must match.
- All EBBs in a `jump_table` must take no arguments.
- Function calls are type checked against their signature.
- The entry block must take arguments that match the signature of the current function.
- All `return` instructions must have return value operands matching the current function signature.

Ad hoc checking:
- Stack slot loads and stores must be in-bounds.
- Immediate constraints for certain opcodes, like `udiv_imm v3, 0`.
- Extend / truncate instructions have more type constraints: Source type can't be larger / smaller than result type.

**Comment by stoklund** [comment]
More ad-hoc checks:

- `insertlane` and `extractlane` instructions have immediate lane numbers that must be in range for their polymorphic type.
- `swizzle` and `shuffle` instructions take a variable number of lane arguments. The number of arguments must match the destination type, and the lane indexes must be in range.

**Comment by mrrrgn** [comment]
The direction I'm currently heading WRT overall structure and testing. The testing will need to be refactored to isolate some repeated code. https://github.com/mrrrgn/cretonne/commit/17303baa8195d4fd68d31c0e6ad682d3d5130d3f

**Comment by stoklund** [comment]
This is looking good! A few comments:

The entity references like `Inst` and `Ebb` implement `Display`, so they print nicer with `{}` than `{:?}`, IMHO.

In the `verifier.rs` module, you could add a public function:
```rust
pub fn verify(func: &Function) -> Result<(), String> {
    Verifier::new(func).run()
}
```
This is easier to use than the two-step create a `Verifier`, call `run`. You could then even make the `Verifier` struct private to the module.

I'd prefer to use the term *terminator* everywhere, so rename `is_terminating` to `is_terminator`.

Being a terminator instruction should be a property of the *opcode*, not of the instruction format. The instruction format is simply computed from the kind of operands the instruction takes, so it can't really be used to infer anything other than how an instruction is represented in memory.

Eventually, I want `Opcode::is_terminator()` to be generated automatically from the meta instruction definitions. I even added some `is_terminator=True` to `meta/cretonne/base.py`, but they are not used for anything yet.

In the meantime, just implement `Opcode::is_terminator()` manually.

**Comment by stoklund** [comment]
Opened #12 to track the opcode flags like `is_terminator`.

**Comment by mrrrgn** [comment]
Whoops, I just saw the above suggestions, will fix them asap. In the meantime, I'm adding more checks. I'm curious about how to handle ``Call`` results in ``instruction_integrity`` as I've started on it here: https://github.com/mrrrgn/cretonne/commit/dff05c900116474780831c0ed11af66b6ab83067

**Comment by stoklund** [comment]
> I'm curious about how to handle `InstructionData::Call` results in instruction_integrity as I've started on it here: mrrrgn@dff05c9

Yeah, that makes sense. The IR data structure is missing some stuff you'll need for verifying function calls. This is what I have in mind:

There will be two kinds of call instructions, *direct* calls and *indirect* calls. A direct call will have an external function entity reference as its callee. These external functions must be declared in the preamble as described in the [language reference](http://cretonne.readthedocs.io/en/latest/langref.html#function-calls). An indirect call will reference a signature entity.

I imagine we'll add something like this to `ir::Function`:

```rust
pub ext_funcs: EntityMap<ExtFunc, ExtFuncData>,
pub signatures: EntityMap<Signature, SignatureData>,
```

In either case, you should be able to get your hands on a signature that you can use to verify both argument and return types.

**Comment by DemiMarie** [comment]
I think that there should be an (optional) component that does safety checks: a safe module cannot corrupt memory.

**Comment by stoklund** [comment]
Safety in Cretonne is expressed by using a reduced instruction set. Specifically, the `heap_load` and `heap_store` instructions are bounds-checked, while `load` and `store` can access all memory. We don't have a way of tagging safe instructions at the moment, but when we do, it would make sense to have the verifier check that only the permitted instruction sets are in use.

**Comment by bnjbvr** [comment]
@leurfete, are you still working on this? If not, would you mind that I take this over, basing my work upon your commits?

**Comment by angusholder** [comment]
For "Values must be defined by an instruction that exists", I'm currently just looping through all values in `dfg.extended_values`, is this the right idea? As far as I know, the only other values possible are the primary result values of instructions, and they only exist when an instruction exists right?

**Comment by stoklund** [comment]
I think there can be dead values in `dfg.extended_values`, and that's OK. You should only check values that are actually used as operands on an instruction. So basically your `verify_value()` function.

You can use `dfg.value_def(value)` to see where the value is defined. Then you can verify that the EBB or defining instructions are valid references and the they are inserted in the layout. See `layout.is_ebb_inserted()` and `layout.inst_ebb()`.

**Comment by angusholder** [comment]
For some of these checks I need a `ControlFlowGraph` and a `DominatorTree`, what should I do for that? Make a separate `verify_context` that takes a `&Context`?

**Comment by stoklund** [comment]
I think you should always compute a dominator tree from scratch if you need it. We can't trust that the one in `Context` is correct. You can use the `Verifier` struct as your context and store it there.

After you compute your own dominator tree, it would be nice to also compare it to the existing one in `Context`. A `verify_context()` function would be good for that.

**Comment by stoklund** [comment]
Same thing for the `ControlFlowGraph`. You can't trust the one in `Context`, so you should compute your own.

**Comment by angusholder** [comment]
Am I right in thinking that `ValueDef::Arg` would always dominate a given instruction in an EBB? Also I don't understand what are value aliases and when would you use them? Are EBB arguments all the values accessible inside that block?

**Comment by stoklund** [comment]
Yes, a `ValueDef::Arg` works like an invisible instruction at the start of the EBB. Other compilers like LLVM use PHI instructions to represent the same thing. You could add a version of `DominatorTree::dominates` that checks if an EBB dominates an instruction.

An instruction is allowed to use all dominating values at that point. That means all values that have been defined no matter what path you take from the entry block to reach the instruction. In practice, that means:

- Values that are defined by instructions earlier in the same block.
- Arguments to the EBB where the instruction is located.
- Values that are defined by a dominating instruction in another block. As determined by `DominatorTree::dominates()`.
- Arguments to other blocks that dominate the current block. As determined by the missing function `DominatorTree::ebb_dominates()`.

Value aliases are annoying. They basically work like symlinks in Unix. An alias is a value that is identical to another value. They are needed in Cretonne because we don't have a `replaceAllUsesWith()` function like LLVM does. It comes up when changing the instructions that compute a given value. Here's an example from `filetests/isa/riscv/expand-i32.cton`:

```
function carry_out(i32, i32) -> i32, b1 {
ebb0(v1: i32, v2: i32):
    v3, v4 = iadd_cout v1, v2
    return v3, v4
}
; check: $v3 = iadd $v1, $v2
; check: $(cout=$V) = icmp ult, $v3, $v1
; It's possible the legalizer will rewrite these value aliases in the future.
; check: $v4 -> $cout
; check: return $v3, $v4
```

RISC-V doesn't have an add with carry instruction, so `iadd_cout` gets expanded into two instructions: `iadd` and `icmp ult`. When we make that change, we need to make sure that `v4` ends up with the result of the `icmp ult` instruction. This is done by changing the `v4` value into an alias of the `icmp ult` result value.

As far as the verifier is concerned, you should just call `dfg.resolve_aliases()` whenever you encounter an alias. Functions like `dfg.value_def()` already do that for you.

**Comment by angusholder** [comment]
Alright I understand the feedback you gave in the PR, I'll fix that in a bit. 

I'm currently working on the type checking - when type checking the arguments of an instruction, should they all have the same type as the controlling type variable? And how do I determine expected types for a non-polymorphic instruction? Here is what I have currently:

    fn type_check(&mut self, inst: Inst) -> Result<()> {
        let ref inst_data: InstructionData = self.func.dfg[inst];
        let constraints: OpcodeConstraints = inst_data.opcode().constraints();

        if let Some(value_typeset) = constraints.ctrl_typeset() {
            // Polymorphic instruction
            let ctrl_type = inst_data.ctrl_typevar(&self.func.dfg);

            if !value_typeset.contains(ctrl_type) {
                return err!(inst, "has an invalid controlling type {}", ctrl_type);
            }

            let fixed_results = constraints.fixed_results();
            if fixed_results >= 1 {
                let expected_type = constraints.result_type(0, ctrl_type);
                let ty = inst_data.first_type();
                if ty != expected_type {
                    return err!(inst, "expected 1st result type {}, found {}", expected_type, ty);
                }
            }

            if fixed_results >= 2 {
                let expected_type = constraints.result_type(1, ctrl_type);
                let ty = self.func.dfg.value_type(inst_data.second_result()
                    .expect("Opcode's constraints say it has a 2nd result, but none was found"));
                if ty != expected_type {
                    return err!(inst, "expected 2nd result type {}, found {}", expected_type, ty);
                }
            }
        }
        Ok(())
    }

As far as I can see, the most fixed arguments any instructions currently have is 2, so I guess I'll assert that for now.

Also how should I go about checking that two `DominatorTree`s are the same? `EntityMap` doesn't have `PartialEq` derived currently, would I be ok to add it?

**Comment by stoklund** [comment]
There's two models for the type variables and operand constraints:

- The Python meta-language lets you use type variables arbitrarily, so input and output can be fixed types or determined by a type variable.
- The Rust implementation restricts this [as described here](http://cretonne.readthedocs.io/en/latest/metaref.html#restricted-polymorphism) in order to simplify the tables. This is where the "controlling type variable" comes in.

An instruction *result* can be a fixed type or a type computed from the controlling type variable. In either case, the `OpcodeConstraints::result_type()` method can compute the required type.

An instruction *input operand* can be constrained in the same ways as a result, but it can also be independent of the controlling type variable. This is the `OperandConstraint::Free(_)` variant. A freely varying type variable is constrained to a specific `ValueTypeSet`.

There are missing methods on `OpcodeConstraints` for accessing the input constraints. I think we need something like this:

```rust
pub enum ArgumentConstraint {
    Bound(Type),
    Free(ValueTypeSet),
}

impl OpcodeConstraints {
    pub fn value_argument_constraint(self, n: usize, ctrl_type: Type) -> ArgumentConstraint {
        assert!(n < self.fixed_value_arguments());
        ...
    }
}
```

The data needed to implement this method should already be present in the `OPERAND_CONSTRAINTS` table.

For non-polymorphic instructions, `ctrl_typevar()` should return `VOID`, and the corrresponding `result_type()` and `value_argument_constraint()` functions should be happy to accept that for `ctrl_type`. They won't need to look at it since the `OPERAND_CONSTRAINTS` table has concrete type entries for these instructions.

The code you pasted for checking result types looked good, except you should use the `dfg.inst_results().take(fixed_results)` iterator to get all the fixed result values.

# Special constraints

The meta language type variables can only describe when the type of one operand is the same as or a set function of the type of another operand. It can't describe the case where two type variables can vary in a dependent way. For example:

```
a = ireduce x
```

This instruction is currently defined with two independent type variables, but that's not right. The two variables should have the same number of vector lanes, and the lanes in `a` should not be wider than the lanes in `x`.

This kind of constraint need to be checked by custom verifier code.

# Comparing dominator trees

A dominator tree is completely described by the immediate dominators, so just check that `idom()` returns the same for all EBBs. Let's not worry about the RPO numbers yet. I'm not sure they would be deterministic if we allow incremental dominator tree updates.

If the trees do differ, I think we want a better error message than "No!", so a `PartialEq` implementation on `EntityMap` is probably not that useful.

**Comment by stoklund** [comment]
I added the missing `value_argument_constraint()` function.

**Comment by stoklund** [comment]
The type-checking verifier is already funding bugs: de543bb30843cffd20516b23fb0c2f8ceeecdc06 and 62641d4553b7cc673cd1543f92b32ef0f8ebe2d5. This is great!

**Comment by Techcable** [comment]
It seems the verifier's safe subset is primarily designed for garbage counting collectors, while I need support for reference counting in my JIT compiler. Is that feature already being considered at this point, or would I need to implement it myself?

**Comment by stoklund** [comment]
@Techcable, Cretonne doesn't have support for any kind of garbage collection at the moment, whether tracing or reference counting. It is a lower-level code generator, and those things are usually handled by the embedding virtual machine.

Cretonne may in the future provide some help for a tracing garbage collector to find its roots on the stack. But that will still be a low-level mechanism that a higher-level GC implementation can use.

**Comment by sunfishcode** [comment]
I believe all the main ideas here are now implemented in the verifier.
