### ISSUE TITLE
Use types to distinguish between wasm function body indices and wasm function indices

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#343]
The function index space of a WebAssembly module includes the imported functions, followed by the functions defined in the module. Unfortunately, this is often error prone, because if one has indices into eg. the Function or Code sections, those index spaces don't include the imported functions, and it's easy to get such indices confused with indices into spaces that do include the imported functions.

It'd be nice if we could have a distinct types for each of the two kinds of indices, to catch common errors where one performs indexing with the wrong type. For example, `DummyModuleInfo`'s `functions` includes imports, while `function_bodies` doesn't, which would be a good place to start. One way to do this would be to convert them from `Vec` to `PrimaryMap`, which is essentially a `Vec`, but which has infrastructure for declaring specialized index types. lib/codegen/src/ir/entities.rs has examples of declaring dedicated index types for use with `PrimaryMap`.

**Comment by lachlansneff** [comment]
Yeah, this has bitten me a couple of times.

**Comment by mlea13** [comment]
I only have a little bit of experience with Rust but the CraneLift project looks really cool and I'd love to try to help! I was thinking this might be a good place to start?

Just took a quick look at the code. Is there anything special about the `EntityRef` trait defined in lib/entity/src/lib.rs or would it be just as good to use two types that map to a usize similar to the Index types in lib/wasm/src/translation_utils.rs and then have a enum type that could be either of those?

**Comment by sunfishcode** [comment]
Yes, I think this would be a good place to start!

The purpose of EntityRef and PrimaryMap is to have indicies that can't be acxidentally used in the wrong space, using types. If one mistakenly uses a `FunctionIndex` in the `function_bodies` array today, it's a bug. If we used PrimaryMap and EntityRef, they would make this a type error -- at compile time.

An enum would keep track of the kind dynamically. That would make such a bug a runtime error, which would be nicer than letting the bug propagate, but not as nice as a compile-time error :-).

**Comment by mlea13** [comment]
Ah okay, yeah makes sense!
