### ISSUE TITLE
Rename Cretonne?

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#362]
From a wide variety of feedback, it seems an obscure, thick cotton fabric that was once popular for making curtains isn't directly inspiring for many people.

On the other hand, Cretonne does have some amount of name recognition at this point, and its weakness makes it's strength in being easy to search for.

**Comment by phase** [comment]
As a super longtime lurker of Cretonne, I believe a dead term is a _perfect_ name for a project. A mascot might be a little difficult to create for _cotton fabric_, but I'm sure we can think of something <small>(a cloth wiping the rust off of something? can't be worse than the new go logo)</small>. This project is already the first result (for me) when googling `cretonne`, and there isn't really a reason to change the name. <small>I actually didn't know that was an English word until you said it was.</small>

**Comment by lachlansneff** [comment]
I actually do like the name. As @phase said, a logo might be a tad difficult, but not impossible.

**Comment by glaebhoerl** [comment]
(Just as a data point, my brain had up until reading this unknowingly conflated the word with *crouton*.)

**Comment by pepyakin** [comment]
my data point is same as @glaebhoerl 's

**Comment by sunfishcode** [comment]
I've heard other people think it's crouton too. And others, *cretin*.

I agree that Cretonne *can* work, and we can eventually figure out a logo. On the other hand, it's not the only possible name which would be easy to search for. If something better comes up, it's worth considering.

**Comment by kazimuth** [comment]
Logo idea: what about a loom? A loom seems like a reasonable metaphor for a compiler. Plus, Jacquard looms were an important step in the history of computing, because they used punched cards; and also, they were way faster than their predecessors :)

**Comment by MaxGraey** [comment]
### How about that logo? (inspired by fabric patterns)

![crettone-logo](https://user-images.githubusercontent.com/1301959/41440125-0e4102d2-7036-11e8-84aa-540686a11b68.jpg)

### And encode 'C', 'T', and two variants of 'N'.

**Comment by tyler** [comment]
That's really clever. I like that.

**Comment by MaxGraey** [comment]
More colour variants:
![crettone-variants](https://user-images.githubusercontent.com/1301959/41497991-85a25bf2-716a-11e8-9978-a4477a90f99f.jpg)

**Comment by lachlansneff** [comment]
Those do look quite good. Could you try one with rounded corners on the inner parts?

**Comment by MaxGraey** [comment]
What looked like a assembled puzzle?

**Comment by MaxGraey** [comment]
![crettone-logo-2](https://user-images.githubusercontent.com/1301959/41499812-97353522-718f-11e8-8cfc-4ee8b7a1abe6.jpg)

**Comment by MaxGraey** [comment]
![crettone-logo-3](https://user-images.githubusercontent.com/1301959/41499906-9639eb5c-7191-11e8-80f8-2a8186d86e94.jpg)

**Comment by sunfishcode** [comment]
I trust no one intended it this way, but: I will not support any logo which has even a small risk of being interpreted as a swastika.

**Comment by MaxGraey** [comment]
@sunfishcode thanks for the feedback. Hmm, until you noticed I could not see it. But this point of view inherent probably more to Europeans, because in many nations this often has quite the opposite meaning:

![swastics](https://user-images.githubusercontent.com/1301959/41506200-09794032-7222-11e8-906a-80afd997a666.jpg)

**Comment by sunfishcode** [comment]
I am aware of the history. I ask everyone to accept that this issue is very important to me personally. If anyone wishes to discuss this further, they're welcome to contact me privately.

On a different topic, while I appreciate your ideas and efforts so far, please keep in mind that the question of the name is still open, which could have a significant effect on what kind of logos we'll want 🙂.

**Comment by MaxGraey** [comment]
Certainly the issues of historical events related to the ancestors, as well as religious issues are always very personal and I certainly wouldn't go into this topic. 👍

**Comment by kinggoesgaming** [comment]
wow... what exactly happened here? @sunfishcode you went on a rampage...

**Comment by lachlansneff** [comment]
@kinggoesgaming Nothing productive was happening.

**Comment by sunfishcode** [comment]
Some thoughts:
 - It takes creativity, skill, and work to create a logo that looks good and conveys useful ideas, in a variety of media, at a variety of sizes, just on a logo's own terms. But on top of that, logos necessarily participate in external commercial and cultural visual languages, regardless our intentions or even our awareness.
 - Some otherwise appealing logo ideas were proposed here with the best intentions, but which inadvertently carried some risk of unwanted meanings. After a brief discussion, I believe all involved now share a sufficient common understanding.
 - I made the judgement call that further discussion of that subthread from others would be unlikely to be productive, and could conceivably end up being misinterpreted if anyone should read parts of the thread without the full context.

My own preference at this time is to take a little more time to resolve the question of naming, before considering logos. As I've said above, while "cretonne" isn't the easiest thing to design logos for, I'm confident that we can find something in any case.

Also, when it comes time to figure out a logo, my preference would be to figure out a process first, so that we can establish appropriate expectations.

**Comment by vitiral** [comment]
So... I had always thought Cretonne was actually [Creatine](https://en.wikipedia.org/wiki/Creatine)... this isn't really you're fault or anything and shouldn't necessarily play in whether or not to rename it... but thought you should know that _some people_ thought your project's name was based on a protein supplement typically used by body builders XD

**Comment by phase** [comment]
A counterpoint to my original comment that I thought of is that the name doesn’t include any indications as to what the project is. LLVM, JVM, and other similar acronyms contain _what they are doing in the title_. “Cretonne” doesn’t have this, and that may be an issue for people searching for “a rust code generator” and not thinking to look up fabric. “RGC” is an example of an ugly name that communicates to the user that the project is a _Rust code generator_. This may be something you want to take into consideration.

**Comment by 6A** [comment]
Very few project names are logical though. Rust has nothing to do with programming, for instance ; the C# compiler is known as Roslyn ; and until recently I did not know that LLVM stands for "Low Level Virtual Machine." I'm probably biased because I now know what Cretonne is, but I had probably never seen that word before, and now I instantly associate Cretonne not with the fabric, but with this project.

**Comment by ehiggs** [comment]
I don't think one needs much creativity in making a logo. [An image search for Cretonne shows many beautiful images](https://duckduckgo.com/?q=cretonne&t=ffab&iax=images&ia=images) that could be leaned on in the way that OReilly leans on lithographs of animals. A pattern of Ferris crabs spread across an image with a filter giving it the texture of actual cretonne is an example you can pluck from the air with little or no effort.

**Comment by sunfishcode** [comment]
I've now settled on a new name: Cranelift! The github repo and everything else is updated, though if I've missed anything, please report it. "cranelift" can be abbreviated as "clif" in some contexts, so we now have "clif-util" and ".clif" files (credit to @lachlansneff  for spotting that opportunity :-)).

**Comment by phase** [comment]
Well that was insanely fast. I didn't expect to see the project undergo a rename over night without any community input, but I guess this new name is okay. It's still named after a random object which is just as strange. If there was some reasoning behind the name I'd love to hear it. #RIPCretonne

**Comment by 6A** [comment]
I also liked cretonne much more, but I'm sure I'll get used to the new one quickly.

**Comment by sunfishcode** [comment]
Reading through the comments here again, I can see how the rename was surprising, so here's more backstory:

I've been anxious to resolve this issue, one way or another, and have been unable to find a replacement that I felt good about for months. And the longer we wait, the harder it'll be. So once I had a name, had heard good things from some pings about it and some research, I decided to just go with it. Naming feels like the kind of highly subjective thing that's hard to do by committee, even if I do otherwise want to avoid becoming a BDFL as the project matures.

Since then, I've gotten feedback that "crane" sounds like the French word for "skull", and Crane-related names like CraneStation evoke images of graveyards. And more people have either raised their preferences for Cretonne, or expressed a lack of enthusiasm about Cranelift, joining the people on this thread.

So, I'm re-opening this issue, and I'll consider "Cranelift" to be a provisional name for now.

**Comment by MaxGraey** [comment]
Hmm, choose great name is always hard for me as well. So sometimes I use Ai name generator [like that](https://namelix.com/app/?keywords=compiler+low+level)

**Comment by 6A** [comment]
Finding a suitable word is indeed very hard. If it's any consolation though, I am French and did not think about the word "crâne" once. 

I'm curious about something else though, why have both the names "CraneStation" and "cranelift"? Among these two, I like the latter much more.

**Comment by phase** [comment]
> I'm curious about something else though, why have both the names "CraneStation" and "cranelift"? Among these two, I like the latter much more.

I believe `CraneStation` is the name of umbrella project that other smaller projects might fall into, if they should appear.

**Comment by sunfishcode** [comment]
@MaxGraey That Namelix generator is fun. It likes the name "Compilerr", which is too true ;-).

**Comment by MaxGraey** [comment]
Wow, this Ai is smarter than I thought =)

**Comment by nnethercote** [comment]
http://aux.messymatters.com/pgnames.html has some good suggestions about criteria for a good name. "CraneLift" does better by those criteria than "Cretonne".

**Comment by 6A** [comment]
I can confirm I'm used to it as well.

**Comment by pepyakin** [comment]
I'm the one who actually likes the name : )

**Comment by sunfishcode** [comment]
"Cranelift" has been continuing to settle in since my [last post](https://github.com/CraneStation/cranelift/issues/362#issuecomment-4079723450, so I think we can close this now. Thanks to everyone for their patience!
