### ISSUE TITLE
Add a `readonly` flag for loads

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#366]
See the discussion in https://github.com/Cretonne/cretonne/issues/278#issuecomment-375734141. That comment also imagined a "MutableGlobal" flag, but that's more complex and not presently needed, so let's defer it. 

The steps are roughly:
 - Add a readonly flag to MemFlags, similar to notrap, and document it in ir.rst. The behavior is undefined if the dereferenced memory is mutated at any time between when the function is called and when it is exited.
 - Add a verifier check to reject stores marked readonly. This doesn't quite fall under `instruction_integrity` or others, so lets add a new function in the loop in lib/codegen/src/verifier/mod.rs's `run`, called `immediate_constraints` or so and check it there.
 - Make the legalization for `deref` global values add the `readonly` flag, in `deref_addr`, and mention this in the comments/documentation for `GlobalValueData::Deref`/`deref`.
 - Remove `can_load` from simple_gvn's `trivially_unsafe_for_gvn`, and make gvn check that if the instruction `can_load`, it's valid to consider only if it's one of the load instructions with `readonly`. In theory, gvn should Just Work, because it's hashing the `InstructionData`, so two loads with the same address and flags will automatically look the same.
 - Write a `legalizer` test that tests multiple accesses to a heap with a deref base, and the redundant base computation should be eliminated.

**Comment by lachlansneff** [comment]
I'll do this.

**Comment by sunfishcode** [comment]
One other issue that comes up here: Instructions like `load_complex` have a `ValueList` in their `InstructionData`, so that they can hold more operands than may fit in an `InstructionData`. `Valuelist` is `entity::EntityList<Value>`, which [doesn't really](https://github.com/cretonne/cretonne/blob/master/lib/entity/src/list.rs#L81) implement `Hash`. This is because `EntityList` doesn't actually hold a pointer to the operands, instead it just has an index into a pool, which must be provided separately whenever accessing elements. I don't yet know how best to fix this.

**Comment by sunfishcode** [comment]
#388 is now merged, so the issue I brought up here should no longer be a concern!

**Comment by lachlansneff** [comment]
Just noting here that I am planning to actually do this within the next few days. Had completely forgotten about it until @sunfishcode politely reminded me.
