### ISSUE TITLE
Global values-related errors are not correctly reported

### ISSUE THREAD

**Issue by 6A** [CraneStation/cranelift#385]
While working on fixing #376, I discovered that errors that take their position on a global value are not correctly reported.

For example, the following file test succeeds:

```cton
test verifier

function %vmglobal_err(i64) -> i64 {
    gv4 = vmctx+0 ; error: undeclared vmctx reference
ebb0(v0: i64):
    v1 = global_value.i64 gv4
    return v1
}
```

However, when trying to compile the following code,

```cton
target x86_64

function %vmglobal_err(i64) -> i64 {
    gv4 = vmctx+0
ebb0(v0: i64):
    v1 = global_value.i64 gv4
    return v1
}
```

the following error is reported:

```
function %vmglobal(i64) -> i64 fast {
    gv0 = globalsym %
    gv1 = globalsym %
    gv2 = globalsym %
    gv3 = globalsym %
    gv4 = vmctx

ebb0(v0: i64):


}
```

As you see, no error message is shown, even though it **is** reported.

## Edit
Looks like this would be fixed by making `decorate_function` also take a function that can decorate the preamble in `write_preamble`. Then in `pretty_verifier_error` we could pass another closure that decorates global values-related errors.

I can take care of it; if you have some specific requests please tell me.

**Comment by sunfishcode** [comment]
With all of @6A's recent changes, the verifier error is now reported like this:
```
function %vmglobal_err(i64) -> i64 fast {
    gv0 = symbol %
    gv1 = symbol %
    gv2 = symbol %
    gv3 = symbol %
    gv4 = vmctx
    ^~~~ verifier gv4: undeclared vmctx reference gv4


ebb0(v0: i64):
    v1 = global_value.i64 gv4
    return v1
}
```
So this issue is now fixed!
