### ISSUE TITLE
Rework verifier

### ISSUE THREAD

**Issue by 6A** [CraneStation/cranelift#387]
The `Verifier` has two main flaws:
- Error messages are arbitrary strings, and do not carry much information (see #284).
- Error messages cannot be reported in batch; if multiple errors are present, one error will only be diagnosed once the previous one is fixed.

## Carry more information
The first issue can be fixed by having specific codes for each diagnostic. I'm sorry to bring in my own project, but [here is how I personally handled diagnostics in my compiler](https://github.com/6A/styx-history/blob/c1bff1983e2faf5ce7deadb281ee0a936dafadd1/styx.rs/src/diagnostics.rs#L348-L607).

Diagnostics have a severity (optional here in Cretonne), a code, a message and a span (the two latter are already in Cretonne). Additionally, the `DiagnosticCodes` struct exists, and lists all existing diagnostic codes.

Finally, diagnostics are defined using a macro that adds a function for each diagnostic, as well as a const in the `DiagnosticCodes` struct.

For instance,
```rust
def_error!(0x20, undefined_symbol, symbol: &str => "Undefined symbol '{}'.");
```

would produce
```rust
impl DiagnosticCodes {
    /// Identifiying code of the `undefined_symbol` `Diagnostic`.
    #[allow(non_upper_case_globals)]
    pub const undefined_symbol: usize = 0x20;
}

impl Diagnostic {
    /// (Error) `Diagnostic` with message "Undefined symbol '{}'.".
    #[inline]
    pub fn undefined_symbol(span: Span, symbol: &str) -> Self {
        Self::error(DiagnosticCodes::undefined_symbol, format!("Undefined symbol '{}'.", symbol), span)
    }
}
```

## Report in batch
The verifier has steps that are executed sequentially. Instead of returning `Result<(), VerifierError>`, we could pass a `&mut Vec<VerifierError>` to each sub function, which would then report errors. Furthermore, if a function returns `false`, we consider the error fatal and stop the process right away, since further checks may expect this one check to succeed.

Finally, depending on whether our vector is empty, we consider the function either valid or invalid.

**Comment by sunfishcode** [comment]
Interesting! The background here is that we don't expect Cretonne IR to be written by hand in large quantities. A verifier error typically indicates a bug in whatever produced the IR, so we tend to think of a verifier error as an alternative to `panic` that gives applications the option of not crashing.

That said, I can see the value in making it more human-friendly. Reporting in batch sounds like a good idea.

I'm curious about what you would use diagnostic codes for. I'd naively expect an application to respond to a verifier error by abandoning the current compilation, regardless of what specific error was detected. Do you envision something different?

**Comment by 6A** [comment]
That sounds fair, I understand why we report errors one by one then.

These ideas come from the top of my mind and do sound uncommon, but I think they could still be considered:

- For one, we could later introduce optional safety checks that are enabled by default but that can be disabled, in case the end user truly knows what they're doing. Disabling it using a code would be very easy.

- Also, it's possible a compiler would emit code using Cretonne, and only perform type check at the higher level. Thus, Cretonne would catch low-level errors and report them, and the higher-level compiler would re-format the errors, given their code.

There are probably other use cases, but I can't think of any myself.

**Comment by 6A** [comment]
Alright, then I'll work on transitioning from `Result<(), VerifierError>` to `&mut Vec<VerifierError>` tomorrow, unless you have specific requests by then.

**Comment by sunfishcode** [comment]
Just saw your question (Github doesn't send notifications for edits) -- I have a vague sense that capitalizing them would make them a little friendlier.

**Comment by 6A** [comment]
Alright, I'll capitalize them then (and I'll stop editing comments instead of replying directly). I'm still in the process of switching from `VerifierResult` to `&mut Vec<VerifierError>`, since they are used in many functions...

**Comment by 6A** [comment]
Sorry I did not work a lot on this lately. I realized that moving from `VerifierResult` to `&mut Vec<VerifierError>` requires `std`, which is why I'm not sure how to proceed....

However, with how I did things, it might be possible to support both things. For one, I always report errors using macros. `report!` reports an error and continues, whereas `fatal!` reports an error and stops the process (by returning `VerifierResult<()>.Err(())` early). We could set up type aliases such that `VerifierErrors` is `&mut Vec<VerifierError>` in `std`, and `()` in `no_std`, and change the macros so that both `report!` and `fatal!` return early in `no_std`.

**Comment by sunfishcode** [comment]
We can (and do) use `Vec` in no_std mode, as we can use it from liballoc. It just requires an explicit `use std::vec::Vec;` at the top of each file that uses it (and the rest of the magic happens in the `mod std` code in our lib.rs files).
