### ISSUE TITLE
Panic with SimpleJIT + module.define_data

### ISSUE THREAD

**Issue by bjorn3** [CraneStation/cranelift#407]
Relevant code: https://github.com/bjorn3/rustc_codegen_cranelift/blob/static_error/src/constant.rs

Backtrace:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`', cranelift/lib/module/src/module.rs:277:9
stack backtrace:
[...]
   7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   8: <cranelift_module::module::ModuleNamespace<'a, B>>::get_data_definition
             at ./<panic macros>:8
   9: <cranelift_simplejit::backend::SimpleJITBackend as cranelift_module::backend::Backend>::finalize_data
             at cranelift/lib/simplejit/src/backend.rs:317
  10: <cranelift_module::module::Module<B>>::finalize_data
             at ./cranelift/lib/module/src/module.rs:588
  11: rustc_codegen_cranelift::constant::get_global_for_alloc_id
             at src/constant.rs:104
  12: rustc_codegen_cranelift::constant::trans_constant
             at src/constant.rs:42
  13: rustc_codegen_cranelift::base::trans_operand
             at src/base.rs:524
  14: rustc_codegen_cranelift::base::trans_stmt
             at src/base.rs:227
  15: rustc_codegen_cranelift::base::trans_fn
             at src/base.rs:104
  16: rustc_codegen_cranelift::base::trans_mono_item
             at src/base.rs:30
  17: <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
             at src/lib.rs:191
[...]
```

## Reproduction:

```bash
$ git clone https://github.com/bjorn3/rustc_codegen_cranelift.git
$ cd rustc_codegen_cranelift
$ rustup override set nightly
$ rustup component add rust-src
$ git checkout static_error
$ git submodule update --init
$ ./prepare_libcore.sh
$ ./build.sh
```

You may need to run `./build.sh` a few times before this specific errors shows up.

**Comment by sunfishcode** [comment]
I'm attempting to reproduce this, but it hasn't given me the error message above yet, after several runs.

Looking at the error message above, that looks what would happen if there's a data object declared as Local, Preemptible, or Export, and it's not yet defined at the point where another data object which references it is being finalized. Can you tell if it's possible for something like that to happen?

**Comment by bjorn3** [comment]
That shouldn't be possible. I will attempt to create a smaller test case, which always gives this panic.

**Comment by bjorn3** [comment]
Force pushed a small deterministic repro to the `static_error` branch.

**Comment by bjorn3** [comment]
My fault. Accidentally cleared todo list on every loop iteration. Please make the panic message a bit more helpful.

**Comment by sunfishcode** [comment]
I've now added better assertion messages in https://github.com/CraneStation/cranelift/commit/7e789a4d9c3d2a72e70b12993e39ff87c92f0b08.
