### ISSUE TITLE
Move codegen-meta into codegen

### ISSUE THREAD

**Issue by data-pup** [CraneStation/cranelift#415]
We should move `cranelift-codegen-meta` into `cranelift-codegen`.

@sunfishcode feel free to chip in with any advice about doing this, or if publishing the meta crate separately does make more sense. Otherwise, I can try and take care of this sometime this week : )

**Comment by sunfishcode** [comment]
Thanks! I'm learning about these parts of cargo as we go here, so I don't have much advice yet :o). All I have right now is that it'd be nice to avoid publishing the meta crate separately if we can.
