### ISSUE TITLE
thread 'main' panicked at 'attempt to add with overflow'

### ISSUE THREAD

**Issue by bjorn3** [CraneStation/cranelift#432]
```rust
extern crate cranelift_codegen;
use cranelift_codegen::ir::*;
fn main() {
    let mut jt_data = JumpTableData::new();
    jt_data.set_entry(-1isize as usize, Ebb::with_number(0).unwrap());
}
```

```
thread 'main' panicked at 'attempt to add with overflow', lib/codegen/src/ir/jumptable.rs:55:31
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
[...]
   9: cranelift_codegen::ir::jumptable::JumpTableData::set_entry
             at lib/codegen/src/ir/jumptable.rs:55
  10: main
             at src/main:5
[...]
```

**Comment by sunfishcode** [comment]
Nice catch :-). This is indeed a bug.

That said, the comment for `JumpTableData` may also be worth noting: "All jump tables use 0-based indexing and are expected to be densely populated." A jump table with size `-1isize as usize` would be impractically large.

This is a difference from LLVM's switch statement, for example, which supports all manner of case distributions. Ideally we should provide a cranelift-frontend utility library for emitting switch code that might be sparse, not 0-based, or other non-jump-table-friendly patterns, turning them into appropriate combinations of branch trees, integer transforms, and jump tables.

**Comment by bjorn3** [comment]
> "All jump tables use 0-based indexing and are expected to be densely populated."

Didnt know that.

> Ideally we should provide a cranelift-frontend utility library for emitting switch code that might be sparse, not 0-based, or other non-jump-table-friendly patterns

+1

**Comment by sunfishcode** [comment]
I filed https://github.com/CraneStation/cranelift/issues/438 for adding a cranelift-frontend API for lowering switches.

**Comment by bjorn3** [comment]
Should this be closed. The `Switch` api exists now.

**Comment by sunfishcode** [comment]
Actually, ca6ef90b78a8404b4c94ac74ca72452aa2e95e83 removed `set_entry` altogether. So yes!
