### ISSUE TITLE
Memcpy/Memset lowering

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#439]
Many source languages need to emit small object copies and initializations. For small sizes, it's efficient to emit load and store instructions inline, and for larger sizes, it's often best to just call the libc `memset` or `memcpy` functions.

Cranelift should have a way to conveniently lower object copies and initializations. One way to do this would be to add code to cranelift-frontend which exposes API functions that take a description of the memory to be copied or initialized, including its size and optionally alignment, and them emits lowered Cranelift IR, either using loads and stores in small cases, or by calling the libc routines otherwise.

There are additional optimizations that can be done, but this would be a good start.

**Comment by bjorn3** [comment]
https://docs.rs/cranelift-frontend/0.44.0/cranelift_frontend/struct.FunctionBuilder.html#method.emit_small_memcpy exists since https://github.com/CraneStation/cranelift/pull/561.
