### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Batarian711** [CraneStation/cranelift#442]
I like open source projects. I want to design a logo for you. Do you have an idea? I will make a gift.

**Comment by sunfishcode** [comment]
Thanks for the offer! Ideas from the name could be long-necked birds, tall hoisting machines, or other things.

We're not urgently looking for a logo, so we don't have a decision-making process in place yet, but maybe we can put something before the Core Team to decide on, once we're ready.

**Comment by MSleepyPanda** [comment]
Just passing by, if its going to be a machine, i think it would be nice if it integrates the rust logo as a gear.

**Comment by sunfishcode** [comment]
If anyone wants to propose a logo, they're welcome to reopen this, or file a new issue.
