### ISSUE TITLE
Any plans for toolchains in the future?

### ISSUE THREAD

**Issue by brunoczim** [CraneStation/cranelift#469]
I was wondering if there is any plans for cranelift having toolchains like: generating text assembly, generating target object files, etc.

**Comment by sunfishcode** [comment]
Cranelift supports generating target object files today, via cranelift-faerie, which connects cranelift to the faerie object file writer. It's capable of writing out ELF and macho .o files, and it could be extended to handle more formats in the future.

Cranelift's current machine-code framework isn't well suited to support text assembly right now though. All we can do right now is give you the text from disassembling the binary machine code. That said though, there are a lot of things we want to do that the machine-code framework isn't well suited for, so I expect we'll be doing some major refactoring/rewriting in the future anyway, and generating text assembly is something we could potentially make easier through this work.

**Comment by brunoczim** [comment]
Thank you very much!
