### ISSUE TITLE
How to reverse the bits of an integer?

### ISSUE THREAD

**Issue by bjorn3** [CraneStation/cranelift#476]
https://doc.rust-lang.org/nightly/core/intrinsics/fn.bitreverse.html

**Comment by sunfishcode** [comment]
Cranelift doesn't have an easy way to do that just yet. We should add it as an instruction in Cranelift IR.

**Comment by Aaronepower** [comment]
This can be closed now with the merge of #486

**Comment by sunfishcode** [comment]
Closing, thanks!
