### ISSUE TITLE
Does cranelift have 'global instruction selection' equivlant or even faster?

### ISSUE THREAD

**Issue by lygstate** [CraneStation/cranelift#482]

**Comment by sunfishcode** [comment]
(Are you referring to global isel in LLVM?) Cranelift's instruction selection is designed to be very fast, though we have't done a lot of tuning yet so there are opportunities to improve.

**Comment by lygstate** [comment]
Yeap Global ISel in LLVM, is there any different design from Global ISel, or that's the same design.
Global ISel may consider a lot more  i know:)

**Comment by sunfishcode** [comment]
If you have any other questions about Cranelift's instruction selection, please feel free to ask here or in a new issue!
