### ISSUE TITLE
verifier: Diagnose incorrect uses of INVALID

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#493]
Cranelift [has a VOID type](https://github.com/CraneStation/cranelift/blob/289035f7a136659ad7264cb16c7e0ebedc2b6f9c/lib/codegen/src/ir/types.rs#L23) but it's only used in a few contexts, because in general Cranelift prefers to use an array or vector of types which can be empty. As an example, it's particularly confusing that one can create a function with a return type of VOID, which turns out to be impossible to actually use. We should add verifier checks for this and other possible misuses of VOID.

**Comment by sunfishcode** [comment]
Cranelift's VOID isn't actually used to indicate any actual typing concept, it's just a placeholder for IR data structures that have a type field but don't always need it. To hopefully clear up some of the understandable confusion, I've now renamed VOID to INVALID and updated the comments accordingly.

This issue can remain open, as we should still implement more verifier checks to ensure that INVALID doesn't appear in the IR, such as in function signatures.

**Comment by ash-tamraz** [comment]
Where should the verifier checks to ensure that INVALID doesn't appear in the IR be implemented? I mean in terms of the files. Is it all in `cranelift-codegen/src/verifier`? I'm interested in working on this, where would be a good place to start?

**Comment by sunfishcode** [comment]
Yes, this can be done entirely in `cranelift-codegen/src/verifier`. I think the best way to do this is to add new checks at the top of `Verifier::run` similar to `verify_global_values` etc.
