### ISSUE TITLE
Can't return b8

### ISSUE THREAD

**Issue by bjorn3** [CraneStation/cranelift#496]
```rust
function u0:0(i64 [%rdi], i64 [%rsi]) -> b8 [%rax] fast {
                                ebb0(v0: i64, v1: i64):
                                    v6 = iconst.i64 0
                                    v8 = icmp_imm.i64 ne v6, 1
                                    v9 = bextend.b8 v8
[Op1ret#c3]                         return v9
                                    ^~~~~~ verifier inst4: v9 is a ghost value used by a real [Op1ret#c3] instruction

}
```

**Comment by eddyb** [comment]
Hmm, why are you using `b8`? I thought boolean types were all-zeros or all-ones, whereas Rust's booleans, when represented as a byte, are either `0` or `1`.

**Comment by sunfishcode** [comment]
Yeah, the intention for `b8` and the larger bool types is that they support SIMD (that's why true is all-ones, rather than just `1`). In general, the way to convert a `b1` to an 8-bit `0` or `1` is to use `bint` to convert it to `i8`.

**Comment by bjorn3** [comment]
Got it. Wanted to make the emitted clif to have better represented types.
