### ISSUE TITLE
Make LookupError and SetError implement Fail

### ISSUE THREAD

**Issue by bnjbvr** [CraneStation/cranelift#504]
I'd like to propose that all the errors defined in Cranelift implement the `std::error::Error` trait, so they can be used in Error boxed traits, which are quite convenient to use (e.g. to unify all the possible Result types appearing in signatures of functions called by a given function). This would be a usability improvement, in my opinion.

The trait is right there: https://doc.rust-lang.org/std/error/trait.Error.html

We'd use conditional compilation on the presence of std, to not break non-std builds.

What do people think about this?

**Comment by bnjbvr** [comment]
Another idea is to have a unique `CraneliftError` type that implements the trait, and all possible implementations of `Into<CraneliftError>` for every error type defined by Cranelift.

**Comment by sunfishcode** [comment]
We're currently using [failure](https://github.com/rust-lang-nursery/failure) for error types, which advertises itself to be a successor to `std::error::Error`. It seems somewhat popular, and so far it's worked well for our uses.

Most of our error types implement [`Fail`](https://docs.rs/failure/0.1.2/failure/trait.Fail.html). Users that want to box them and unify them with other errors can use failure's [`Error`](https://docs.rs/failure/0.1.2/failure/struct.Error.html) type (which can also hold instances of `std::error::Error`). `Fail` also provides a [`compat()`](https://docs.rs/failure/0.1.2/failure/trait.Fail.html#method.compat) function which returns an instance of `Compat`, which implements `std::error::Error`, for when that's needed.

So if I understand correctly, if our users can either use `failure::Error`, or `compat()`, then we already provide the functionality that implementing `std::error::Error` would provide.

**Comment by lachlansneff** [comment]
One reason why we decided not to use std::error is so that cranelift would workout without libstd.

**Comment by bnjbvr** [comment]
Interesting, thanks! I opened this issue because I didn't notice the use of `failure`; in particular `isa::LookupError` and `settings::SetError` (both in `codegen`) don't seem to implement it. Should we have them implement the `Fail` trait? (I worked around this by having a new error type that implements `From<T>` for them, so there's a way to circumvent the issue)

**Comment by sunfishcode** [comment]
Ah, yes, `isa::LookupError` and `settings::SetError` do look like good candidates to implement `Fail`.
