### ISSUE TITLE
Does Future Directions for Optimizing Compilers suite for cranelift?

### ISSUE THREAD

**Issue by lygstate** [CraneStation/cranelift#510]
Data-Driven Optimizen?
https://arxiv.org/pdf/1809.02161.pdf

**Comment by pepyakin** [comment]
Before @sunfishcode comes here to give you expanded answer, I will recommend you to take a look to [this document](https://github.com/CraneStation/cranelift/blob/master/rustc.md)

**Comment by sunfishcode** [comment]
If anyone has any further questions here, or is interested in participating, please feel free to ask here, or in a new issue!
