### ISSUE TITLE
COFF object file support

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#511]
To support Rust compilation on Windows, Cranelift will need the ability to emit COFF object files. See https://github.com/m4b/faerie/issues/46 for details.

**Comment by bjorn3** [comment]
I believe cranelift-object supports COFF files.

**Comment by bnjbvr** [comment]
Indeed.

Thanks @bjorn3 for this round of triaging, btw!

**Comment by bjorn3** [comment]
No problem @bnjbvr.
