### ISSUE TITLE
where is crane art?

### ISSUE THREAD

**Issue by chisophugis** [CraneStation/cranelift#514]
I love that crane in https://avatars2.githubusercontent.com/u/11573910?s=200&v=4

Can you upload the artwork somewhere? It's so remixable.

![](https://avatars2.githubusercontent.com/u/11573910?s=200&v=4)

**Comment by sunfishcode** [comment]
I'm glad you like it! I put the SVG file here: https://github.com/CraneStation/cranelift/blob/master/media/crane-ferris.svg
