### ISSUE TITLE
multiple copies of cranelift_codegen::isa::x86::binemit::emit_inst

### ISSUE THREAD

**Issue by froydnj** [CraneStation/cranelift#530]
Landing cranelift in firefox produced [a large regression in installer size](https://bugzilla.mozilla.org/show_bug.cgi?id=1494976#c1).  There are a couple of cranelift functions in the top 100 largest symbols, but these two stand out (readelf output):

```
 68448: 0000000004317a30 62803 FUNC    LOCAL  DEFAULT   16 _ZN17cranelift_codegen3isa3x867binemit9emit_inst17hc9a5f910e87df419E
 68447: 0000000004327120 61669 FUNC    LOCAL  DEFAULT   16 _ZN17cranelift_codegen3isa3x867binemit9emit_inst17h10353c1070eace20E
```

That is, we have two copies of this `emit_insn` function, specialized differently, each weighing in at ~60k.  Is it possible to refactor things so we avoid these separate specializations?

**Comment by sunfishcode** [comment]
The problem is with [`TargetIsa`'s `emit_inst`](https://github.com/CraneStation/cranelift/blob/master/lib/codegen/src/isa/mod.rs#L308). It's not used, outside of tests, however it doesn't get eliminated by LTO because `TargetIsa`'s vtable has a reference to it.

**Comment by sunfishcode** [comment]
#531 is a PR to put `TargetIsa`'s `emit_inst` behind a feature flag, as it's only used by tests. I've now confirmed that this fixes the problem in the SpiderMonkey build.
