### ISSUE TITLE
Eliminate the FunctionBuilder vs FunctionBuilderContext divide

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#567]
Cranelift uses `FunctionBuilderContext` to hold onto memory allocations that can be reused between instances of `FunctionBuilder`s. However, because `FunctionBuilder` has a reference to the `FunctionBuilderContext`, it can't live in the same struct as a `FunctionBuilderContext`, and this can be inconvenient for some frontends, which want to store all Cranelift-related state in a single struct.

I think it'd be good to just merge `FunctionBuilder` and `FunctionBuilderContext`, and allow the result to be cleared while retaining the underlying allocations.

**Comment by Aaronepower** [comment]
Hello, I'd like to work on this issue. I was wondering what the `FunctionBuilder::new` function arguments should be instead?

**Comment by sunfishcode** [comment]
@Aaronepower If you go by my suggestion above, they'd be the same as they are now, but without the `FunctionBuilderContext` argument. 

@bjorn3's suggestion would also work, though I expect it'll be easier for frontends to just have one type to manage, rather than having to switch between one type while translating a function to Cranelift and another type when doing other things.
