### ISSUE TITLE
Bit vs byte mismatch in memcpy/memmove/memset expansion

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#586]
Filing an issue to track [this comment](https://github.com/CraneStation/cranelift/pull/561#pullrequestreview-168443349).

For example in this code:
```rust
            let offset = (access_size * i) as i32;
            let int_type = Type::int(access_size as u16).unwrap();
            let value = self.ins().load(int_type, flags, src, offset);
```
`load` expects the offset to be in bytes, and `Type::int` expects the size to be in bits, so this is missing a unit conversion.

@Aaronepower

**Comment by Aaronepower** [comment]
This can be closed now correct?

**Comment by sunfishcode** [comment]
Yes, thanks!
