### ISSUE TITLE
Update to Rust 2018 edition

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#628]
It's now two weeks after Rust 1.31 is released, as we're following the [Firefox Rust Update policy](https://wiki.mozilla.org/Rust_Update_Policy_for_Firefox), so we can now update to the Rust 2018 edition.

We should update the Rust version in the top-level README.md and .travis.yml.

See [the documentation](https://rust-lang-nursery.github.io/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html) for information on how to transition an existing project to a new edition.

**Comment by mominul** [comment]
I think I can give it a shot 😉

**Comment by mominul** [comment]
@sunfishcode I am having troubles with upgrading codegen crate. This crate uses generated code by the `codegen-meta` crate and python scripts. But the generated codes use old path import syntax. Can you please point me where the module import generation code is?

I am having errors like:
```
error[E0433]: failed to resolve: use of undeclared type or module `ir`
    --> /home/mominul/contrib/cranelift/target/debug/build/cranelift-codegen-628162ebae144856/out/binemit-x86.rs:3730:21
     |                                                          
3730 |                 use ir::condcodes::IntCC::*;             
     |                     ^^ use of undeclared type or module `ir`
```

I guess we only have to change that into `use crate::ir::condcodes::IntCC::*;` etc.
