### ISSUE TITLE
Directory structure for crates

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#647]
Currently Cranelift uses a cargo workspace structure in which there's a top-level crate, and then subcrates under a `lib` directory with shortened names:

   lib/wasm/ - the cranelift-wasm crate
   lib/codegen/ - the cranelift-codegen crate
   etc.

I've not seen any other Rust projects organized in this way. What I have seen is that projects create directories under the top level with the full name of their crates. For Cranelift, that would look something like this:

  cranelift-wasm/
  cranelift-codegen/
  etc.

Has anyone found the `/lib/foo` structure to be confusing? Would the full crate name approach be easier to understand?

**Comment by lazypassion** [comment]
I probably wouldn't have found those crates if I didn't read this issue. I feel like the way rustc is organized is at least easier to discover all the parts of the overall crate.

**Comment by sunfishcode** [comment]
Ok, it sounds like it'd be good to do this. My guess is we should include the `cranelift-` prefixes, to separate the from the non-crate directories. Is anyone interested in working on this? :smiley:

**Comment by lazypassion** [comment]
I'm willing. What would I have to do?

**Comment by sunfishcode** [comment]
You'd have to rename the directories, update the paths in the top-level Cargo.toml, as well as changing paths like "../codegen" to "../cranelift-codegen" in the subdirectory Cargo.toml files. And then search for "lib/" in the rest of the tree and update accordingly. And then make sure everything still builds :-).

**Comment by lazypassion** [comment]
Okay sounds good

**Comment by bnjbvr** [comment]
Thanks @lazypassion, closing.
