### ISSUE TITLE
The x64 calling convention (windows) is implemented incorrectly.

### ISSUE THREAD

**Issue by lachlansneff** [CraneStation/cranelift#691]
As per the microsoft [documentation](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2017#example-of-argument-passing-3---mixed-ints-and-floats), floating point registers are picked by their general parameter index, not their fp parameter index.

**Comment by bnjbvr** [comment]
Should be fixed by #693, please re-open if not. Thanks for reporting this issue!

**Comment by CryZe** [comment]
Cool, I'll give it a try later today. Thanks for fixing this :)

**Comment by CryZe** [comment]
https://github.com/CraneStation/cranelift/pull/693/files#diff-08ef6b0c3d44ab300b5158dab40ea830R122

The debug_assert_eq! here is firing for me now. 
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', cranelift\cranelift-codegen\src\isa\x86\abi.rs:122:13
```

So this doesn't seem to work yet, @bnjbvr

**Comment by CryZe** [comment]
I roughly figured out the problem
```rust
/// Return value registers for x86-64, when using windows fastcall
static RET_GPRS_WIN_FASTCALL_X64: [RU; 1] = [RU::rax];
```
this has a single register, but is being passed to Arg::new here
```rust
    let regs = if sig.call_conv == CallConv::WindowsFastcall {
        &RET_GPRS_WIN_FASTCALL_X64[..]
    } else {
        &RET_GPRS[..]
    };

    let mut rets = Args::new(bits, regs, 2, sig.call_conv);
```
which causes the assert to eventually trigger here
```rust
debug_assert_eq!(self.fpr_limit, self.gpr.len());
```
as the fpr_limit is the 2 from the Args::new and the gpr is the static regs array that has a single register.

**Comment by steffengy** [comment]
Likely a function with a float return value, that isn't covered by tests and trips up here since the same code is used for register assignment, I'll look into that case as well.
