### ISSUE TITLE
build fails on arm64

### ISSUE THREAD

**Issue by vielmetti** [CraneStation/cranelift#716]
Building on a Packet c1.large.arm (arm64, ThunderX) system I get this error:

```
error[E0425]: cannot find function `parse_x86_cpuid` in this scope
  --> cranelift-native/src/lib.rs:45:9
   |
45 |         parse_x86_cpuid(&mut isa_builder)?;
   |         ^^^^^^^^^^^^^^^ not found in this scope
error: Could not compile `cranelift-native`.
```

is there arm64 support in this package? I did not expect to get this codepath.

**Comment by bnjbvr** [comment]
What happens is that the method exists if and only if we're on the expected target, but the way `cfg!(...)` is replaced by the boolean value at compile time, meaning that the resulting code is e.g. `if true { parse_x86_cpuid(...) }` (or on your platform, it'd be `if false {`).

I think we need to stub out the function in the other case, or use an additional dependency `cfg-if` to properly do this.
