### ISSUE TITLE
LICM does not hoist safe loads

### ISSUE THREAD

**Issue by lars-t-hansen** [CraneStation/cranelift#726]
On a [dot-product microbenchmark](https://github.com/lars-t-hansen/embenchen/blob/master/micro/wasmdot.js), the entire difference in speed between Ion-generated and Cranelift-generated code is due to the Cranelift code reloading the heap pointer from the tls (vmctx) on every loop iteration, thus increasing memory traffic and dependencies for the subsequent value loads.  Yet this heap pointer load would be safe to hoist - the value loaded never changes, and the load will never trap.

One problem is that licm, unlike gvn, does not consider read-only loads specially - any load is flagged unsafe for licm.  Changing this experimentally, I find that the heap pointer load is hoisted and the performance improves by 15%.  But presumably this hoisting is only safe if the load is also guaranteed never to trap.  So it's possible that that bit of information needs to be encoded, or if it is already encoded it must be used, or the heap pointer load must be encoded in some other way entirely.

**Comment by lars-t-hansen** [comment]
Oooh, we have the notrap() flag for this.

**Comment by bnjbvr** [comment]
Fixed by #727.
