### ISSUE TITLE
[wasm] Make most FuncEnvironment functions fallible?

### ISSUE THREAD

**Issue by bnjbvr** [CraneStation/cranelift#752]
These functions return a direct result instead of a `WasmResult` data structure that could indicate an error: https://github.com/CraneStation/cranelift/blob/master/cranelift-wasm/src/environ/spec.rs#L120-L156 (also `translate_loop_header` below).

What do people think about harmonizing the signatures and have all of them return a `WasmResult`, instead? We have a use case in Spidermonkey where we can fail during e.g. `make_global` if the type is unsupported by Cranelift (because it's a reftype and Cranelift doesn't work for them yet), so it'd be nice to be able to properly abort translation, instead of roughly panicking as we're doing right now.

**Comment by bnjbvr** [comment]
Forgot to add: in this case, it'd be nice that the `WasmError` be extended to have a `User(String)` variant so users can fill in errors with text of their choosing, created with `format!()` and the likes.

**Comment by pchickey** [comment]
This change would be very welcome. I'm fine with the `User` variant taking a string, but it could also use a `failure::Error`, which is used elsewhere in cranelift

**Comment by sunfishcode** [comment]
Sounds good to me too.
