### ISSUE TITLE
[simplejit] Can't make memory readable+executable on SELinux 

### ISSUE THREAD

**Issue by benschau** [CraneStation/cranelift#772]
Probably not that big of an issue, but for my use case, I have to be able to run on a system that's enforcing SELinux.

# To reproduce
You'll need any system that supports SELinux; I use Fedora 30, which has it enforced by default.
You can check whether SELinux is enabled via `sudo getenforce`. If it isn't enforcing, enable it for this test using `sudo setenforce 1`.

    git clone https://github.com/CraneStation/simplejit-demo (problem can be reproduced with
    any invocation of `Memory::set_readable_and_executable()`)

    cargo run
    
    It will fail with:
    thread 'main' panicked at 'unable to make memory readable+executable: SystemCall(0s 
    { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/libcore/result.rs:997:5

For a more simple test case, you can also try running `simplejit-minimal.rs` and Jonathan Turner's [rustyjit](https://github.com/jonathandturner/rustyjit). They'll both fail with the same kind of issue when SELinux is enforced. 

The problem originates from the region crate ala `cranelift-simplejit/src/memory.rs:123`, which ultimately ends up calling `libc::mprotect()`. That's why `rustyjit` fails as well.

# Workaround
Chris Wellons' [A Jit Compiler Skirmish with SELinux](https://nullprogram.com/blog/2018/11/15/) describes the issue and some of his workarounds pretty well, and I've confirmed that his workarounds do indeed work. In particular, what's happening is that when SELinux is enforced, you can't set execute protections on any page allocated on the heap. 

So, you could change the `rustyjit` program to use the `memmap` crate like in this [gist](https://gist.github.com/benschau/6e0156c8e96fc5502479675cb0bc18d3) I made. Just replace the respective files in `rustyjit` and it'll magically work on SELinux- it uses one of the workarounds that Chris describes using an anonymous memory map to set the required permissions. I'm betting that you could apply something similar to Cranelift, though I don't really know what's desirable.

**Comment by benschau** [comment]
#783

**Comment by bnjbvr** [comment]
I think this was fixed by #783, please reopen if it's not the case.
