### ISSUE TITLE
Missing Cranelift IR documentation

### ISSUE THREAD

**Issue by abrown** [CraneStation/cranelift#832]
@bnjbvr, after merging #799 and associated PRs, I no longer see the Cranelift IR documentation I used to see at https://cranelift.readthedocs.io/en/latest/ir.html#vector-operations. I suspect it has something to do with the `meta-python` to `meta` switch but I haven't verified this.

**Comment by abrown** [comment]
When I look at https://github.com/CraneStation/cranelift/blob/master/docs/ir.rst I see an `autoinst` that may no longer be wired up correctly.

**Comment by bnjbvr** [comment]
Right, the meta-python module was used to document instructions. First step would be to fix this by making sure the doc build doesn't depend on the meta-python crate anymore; then it'd be nice to have access to the instructions comments somewhere else (maybe on docs.rs).

**Comment by bnjbvr** [comment]
@sunfishcode is the meta crate published on Crates.io? I'm asking because it seems the documentation that's published [there](https://docs.rs/cranelift-codegen-meta/0.34.0/cranelift_codegen_meta/) seems to be unaware of many data structures / functions. Am I doing something else wrong?

**Comment by sunfishcode** [comment]
It is published on crates.io, but the documentation only includes the things which are visible outside the crate, which right now just `generate` and a few helper routines needed by cranelift-codegen's build.rs. I wonder if there's a setting we can change, or perhaps we could just make more things `pub` in lib.rs.

**Comment by bjorn3** [comment]
```toml
# Cargo.toml
[package.metadata.docs.rs]
rustdoc-args = [ "--document-private-items" ]
```

See https://docs.rs/about for more info about this section.
