### ISSUE TITLE
Update to Rust 1.37

### ISSUE THREAD

**Issue by bnjbvr** [CraneStation/cranelift#841]
Firefox has been using the latest Rustc stable compiler since today, so we could update the latest required version of Rustc any time now.

**Comment by superriva** [comment]
@bnjbvr Just a question. Could you give a source of this report? Thanks.

**Comment by bnjbvr** [comment]
@superriva This is the [Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1563378) where this has been discussed and fixed.

**Comment by bnjbvr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1574275 shows that Firefox now even uses 1.37, so we could even bump it twice.
