### ISSUE TITLE
SparseSet is worse than EntitySet

### ISSUE THREAD

**Issue by nbp** [CraneStation/cranelift#858]
Reading the code of `cranelift-entity`, I noticed that `SperseSet<T>` is implemented using a `SparseMap<T, T>`.  Such `SparseMap<T, T>` stores a `SecondaryMap<T, u32>` which is a dense map of u32 (32 bits per key), where as an `EntitySet<T>` would be a dense map of bits (1 bit per key)

We should replace `SparseSet` by `EntitySet` everywhere, or change the alias such that we default to the `EntitySet` implementation instead of the `SparseMap`.

**Comment by bnjbvr** [comment]
Yeah, agreed. It just seems that the APIs of `EntitySet` and `SparseSet` (inherited from the API of `SparseMap`) are a bit different; see for instance the `insert` method and others. It shouldn't be very hard to implement `SparseMap`'s API with an underlying `EntitySet`, though.

**Comment by lars-t-hansen** [comment]
Memory usage might go up with EntitySet in very sparse circumstances?  I agree SparseSet seems far from ideal, but it is chosen over SecondarySet precisely to conserve memory, so it's worth keeping that in mind when translating.

**Comment by lars-t-hansen** [comment]
@nbp, I was reacting to your comment above that states that EntitySet has one bit per key, which i took to mean one bit per key in the key space; for large key spaces with small sets this would be more space than a reasonable implementation of SparseSet.  Why SparseSet would use as much space as you state above is then mysterious to me, since that representation doesn't look particularly sparse at all...  I agree that given that representation there's no reason for concern in switching, so far as space usage is concerned.

**Comment by XAMPPRocky** [comment]
@nbp I tried implementing this change however I ran into two instances of using `SparseSet` that I need advice on what to change them to before I make my PR.

The first is pretty easy to implement but I'm not sure it's the right behaviour. In [`cranelift_codegen::verifier`](https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/src/verifier/mod.rs#L306) it displays the `SparseSet` as a slice, would you want the same behaviour with `EntitySet`?

The second is that in [`cranelift_codgen::verifier::flags`](https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/src/verifier/flags.rs#L58). It continually pops from the set, and `EntitySet` currently has no `pop` or `remove` implementation. I would be happy to provide an implementation for it if someone could explain how they would expect `pop` for `EntitySet`.

**Comment by nbp** [comment]
@XAMPPRocky For the first case, this is for reporting an error. I think this is fine to have a slice of the elements stored in the set.

For the second case, this algorithm is using a set for traversing. If the original implementer had wish for a specific performance profile they would have selected a queue or stack. A set is by definition unordered. Also this is a verification phase, thus I am fine if you implement `pop` and `remove` as you think is the best for a `set`.  Maybe instead of `pop` you can implement `pop_last` with the following comment: `Remove the value with the largest index from the set`.

Thanks for looking at this issue :)
