### ISSUE TITLE
How to write a function signature with return `Vec<i32>`？

### ISSUE THREAD

**Issue by mokeyish** [CraneStation/cranelift#860]
Here is the function I want to call in cranelift IR.
```rust
#[inline]
fn vec_from_slice1(s: &[i32]) -> Vec<i32> {
    Vec::<i32>::from(s)
}
```

Here is the function signature  for above. **This cause memory *BADACCESS* Error**.
```rust
let mut sig = module.make_signature();
sig.params.push(AbiParam::new(target_pointer_type)); // slice ptr
sig.params.push(AbiParam::new(target_pointer_type)); // slice len
sig.returns.push(AbiParam::new(target_pointer_type)); // vec ptr
sig.returns.push(AbiParam::new(target_pointer_type)); // vec cap
sig.returns.push(AbiParam::new(target_pointer_type)); // vec len
```

**Comment by bjorn3** [comment]
You shouldnt do this. The rust abi is unstable. Also the problem here is that `Vec` currently hapens to be return using an out pointer. (The function gets a pointer to `Vec` as extra argument and stores the return value there.) Could you tell me more about your usecase, so that I may be able to suggest a workaround?

**Comment by mokeyish** [comment]
@bjorn3 Thanks for your quick response.
I use `cranelift` for jit dynamic calculating, it read data from `&Vec<T>`, and output a new `Vec<T>` 
 finally.

**Comment by mokeyish** [comment]
@bjorn3 It seems to return only two `usize`s  at most, The `fn(s: &[i32]) -> (usize, usize, usize)` will cause error,  but `fn(s: &[i32]) -> (usize, usize)`  not.

**Comment by bjorn3** [comment]
Yeah, a tuple of two scalars is normally passed in and returned from a function using two registers as optimization, while three or more is kept in memory. https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/layout/enum.Abi.html.

A way to make it not depend on the unstable abi would be:

```rust
#[inline]
extern "C" fn vec_from_slice1(ptr: *const i32, len: usize, out_ptr: *mut *mut i32) -> usize {
    let s: &[i32] = slice::from_raw_parts(ptr, len);

    /* some computation */
    let vec = Vec::<i32>::from(s);

    let boxed_slice: Box<[i32]> = vec.into_boxed_slice();
    let len = boxed_slice.len();
    *out_ptr = Box::into_raw(boxed_slice);
    len
}
```

**Comment by mokeyish** [comment]
Is it possible to support three scalars? are you planning to support it？Maybe I should use `Box<Vec<T>>` instead of `Vec<T>` .

**Comment by bjorn3** [comment]
I dont know of any plans by rustc to support it. 

> Maybe I should use Box<Vec<T>> instead of Vec<T> .

You should use `*mut Vec<T>` instead in that case. You can convert a box into it using `Box::into_raw` and recreate the box using `Box::from_raw`.

**Comment by mokeyish** [comment]
@bjorn3 OK, Thanks for your suggestion.

**Comment by bnjbvr** [comment]
Closing, assuming this was specifically a bad ABI usage of the rustc backend, and there's not much to do on the Cranelift side. Please let me know if I'm missing anything and if we should reopen this.
