### ISSUE TITLE
AppVeyor badge is broken or leads to a private project

### ISSUE THREAD

**Issue by Lokathor** [CraneStation/cranelift#877]
The Appveyor badge in the readme is a link to Appveyor but it goes to a project that's private or has been moved. Either way the link doesn't work and should be updated.

**Comment by bnjbvr** [comment]
Thanks for reporting an issue!

@sunfishcode Any idea about how to fix this?

**Comment by sunfishcode** [comment]
We should remove the Appveyor badge for now. Wasmtime is currently experimenting with Azure Pipelines, and if that goes well we may switch to that for Cranelift too.
