### ISSUE TITLE
Broken link to InstBuilder in docs

### ISSUE THREAD

**Issue by jyn514** [CraneStation/cranelift#901]
See for example https://docs.rs/cranelift-frontend/0.38.0/cranelift_frontend/struct.FunctionBuilder.html#method.ins which links to https://docs.rs/cranelift-frontend/0.38.0/codegen/ir/builder/trait.InstBuilder.html, which gives a 404. The right URL is https://docs.rs/cranelift-codegen/0.38.0/cranelift_codegen/ir/trait.InstBuilder.html.

**Comment by jyn514** [comment]
https://github.com/deadlinks/cargo-deadlinks might be helpful for checking this in the future, it's also found the following broken links:

- Found invalid urls in /home/joshua/Documents/Programming/rust/cranelift/target/doc/cranelift_codegen/binemit/trait.TrapSink.html:
        Linked file at path /home/joshua/Documents/Programming/rust/cranelift/target/doc/cranelift_codegen/binemit/binemit/trait.TrapSink.html does not exist!
- Found invalid urls in /home/joshua/Documents/Programming/rust/cranelift/target/doc/cranelift/prelude/struct.FunctionBuilder.html:
        Linked file at path /home/joshua/Documents/Programming/rust/cranelift/target/doc/cranelift/function/struct.Function.html does not exist!
        Linked file at path /home/joshua/Documents/Programming/rust/cranelift/target/doc/cranelift/codegen/ir/builder/trait.InstBuilder.html does not exist!
0

**Comment by bnjbvr** [comment]
Nice find! I've found that with the following line:

```
find ./target/doc -maxdepth 1 -type d -name "cranelift*" | xargs -I{} cargo deadlinks --dir {}
```

You get even more failures! Care to submit a patch to fix this? :)

**Comment by bnjbvr** [comment]
Fixed by https://github.com/CraneStation/cranelift/pull/905, thank you!
