### ISSUE TITLE
Float parsing seems incorrect

### ISSUE THREAD

**Issue by abrown** [CraneStation/cranelift#909]
When parsing CLIF floats to `Ieee32`, I noticed that two of the four bytes were zeroes once lowered. Investigating some more, I wrote the following test:

```
#[test]
    fn ieee32_actual_bytes() {
        assert_eq!(
            Ieee32::with_float(1.1).0.to_le_bytes(),
            [0xcd, 0xcc, 0x8c, 0x3f]
        );
        assert_eq!(
            "0x1.1".parse::<Ieee32>().unwrap().0.to_le_bytes(),
            [0xcd, 0xcc, 0x8c, 0x3f]
        );
    }
```

When run, the second assertion will fail:

```
ir::immediates::tests::ieee32_actual_bytes' panicked at 'assertion failed: `(left == right)`
  left: `[0, 0, 136, 63]`,
 right: `[205, 204, 140, 63]`
```

Perhaps I am using the hexadecimal float syntax incorrectly but I don't see an explanation for how I should be correctly writing the value `1.1`. Or this might be due to some error in `parse_float`. What is the intended behavior for parsing floats from CLIF?

**Comment by sunfishcode** [comment]
The behavior is if it starts with `0x`, it's parsed as a hexadecimal floating-point value, otherwise it's parsed as decimal. The first string is a decimal `1.1`, and the second is a hexadecimal `0x1.1`, which in decimal would be `1.0625`.

The value of `1.1` can't be represented exactly in binary floating-point; the closest representable value in `f32` value in hexadecimal is `0x1.19999ap+0`.

**Comment by abrown** [comment]
>  otherwise it's parsed as decimal

I don't think it actually ever is parsed as decimal (https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/src/ir/immediates.rs#L504)--which would be nice--but what you are saying makes sense.

**Comment by sunfishcode** [comment]
Oh, right, it issues an error for a decimal string. I think the situation there is we wanted to avoid pulling in the implementation of `.parse::<f32>()`. But I think it'd be fine if we added it as a `#[cfg(test)]` thing.
