### ISSUE TITLE
Incorrect register movement when SSA value is re-used

### ISSUE THREAD

**Issue by abrown** [CraneStation/cranelift#923]
I was implementing an improvement to SIMD extractlane on x86 to avoid moving floats in and out of XMM registers unnecessarily; e.g. to extract an `f32` from an `f32x4` a `PSHUFD` is used to get the bits in the lowest order positions and the XMM register is re-used. When an SSA value is re-used, I expected cranelift to know that it is re-used and if its register is overwritten ensure the value is previously copied to a different register. I wrote a test for my improvement:
```
test run
set enable_simd
function %test_extractlane_f32() -> b1 {
ebb0:
    v0 = f32const 0x42.42
    v1 = splat.f32x4 v0
    v2 = extractlane v1, 3
    v3 = fcmp eq v2, v0    ; <--- v0 re-used
    return v3
}
; run
```
This fails with the following error:
```
- inst12: RexOp2frmov#428 constraints not satisfied in: regmove.f32 v0, %rax -> %xmm1
function %test_extractlane() -> b1 [%rax] fast {
                                ebb0:
[RexOp1pu_id#b8,%rax]               v4 = iconst.i32 0x4284_8400
[RexMp2frurm#56e,%xmm0]             v0 = bitcast.f32 v4
[RexOp2frmov#428]                   regmove v0, %xmm0 -> %rax
[RexMp2frurm#56e,%xmm0]             v5 = scalar_to_vector.f32x4 v0
[Mp2r_ib_unsigned_fpr#570,%xmm0]    v1 = x86_pshufd v5, 0
[Mp2r_ib_unsigned_fpr#570,%xmm0]    v6 = x86_pshufd v1, 3
[null_fpr#00,%xmm0]                 v2 = raw_bitcast.f32 v6
[RexOp2frmov#428]                   regmove v0, %rax -> %xmm1
[RexOp2fcscc#42e,%rax]              v7 = fcmp ord v2, v0
[RexOp2fcscc#42e,%rcx]              v8 = fcmp ueq v2, v0
[RexOp1rr#21,%rax]                  v3 = band v7, v8
[Op1ret#c3]                         return v3
}
```

I'm not sure I understand how to read `regmove.f32 v0, %rax -> %xmm1`: `%rax` is moved to `%xmm`? `%rax` is now an alias for `%xmm`? If I understood that, perhaps I could decipher what constraints are not satisfied.

In any case, I suspect there is a re-use issue because if I change the test to the following it will pass:
```
test run
set enable_simd
function %test_extractlane_f32() -> b1 {
ebb0:
    v0 = f32const 0x42.42
    v1 = splat.f32x4 v0
    v2 = extractlane v1, 3
    v9 = f32const 0x42.42
    v3 = fcmp eq v2, v9      ; <--- new v9 is used, no re-use
    return v3
}
; run
```

**Comment by abrown** [comment]
I suspect this is not related to my custom legalization, but it might be; here is the custom legalization for this improvement: https://github.com/abrown/cranelift/compare/add-simd-const-x86-refactored...abrown:improve-extractlane#diff-cab93ac591017abedd1e4704ee90af8fR900-R956

**Comment by bnjbvr** [comment]
Hmm, this is probably register allocation doing something fishy here: the regmoves are inserted because of local register diversions, but RegMove instructions aren't defined so they can handle different src and dst types, which seems to be the case here. It's also weird that regalloc decided to divert from one register bank to another one like this.

**Comment by bjorn3** [comment]
https://github.com/CraneStation/cranelift/blob/8977442cb8df2264d24848965b78f77447a6719e/cranelift-codegen/meta/src/isa/x86/encodings.rs#L1678

https://github.com/CraneStation/cranelift/blob/8977442cb8df2264d24848965b78f77447a6719e/cranelift-codegen/meta/src/isa/x86/recipes.rs#L635

`scalar_to_vector` requires a GPR register as input, so regalloc moves the float to a GPR register.

**Comment by bnjbvr** [comment]
Ah right. I now see that the definition of the instruction is incorrect: it says that the input can be any type, and the output can be any type too, independently from the input type. In fact, there should be a VectorOf type derivation (reverse of LaneOf), and the output type should be constrained to the input's VectorOf derived type. The instruction would be type sane, at least, and this would probably trigger a type error, making the problem explicit.

**Comment by bnjbvr** [comment]
(Maybe the type constraint can already be defined by using a vector as the output type, and the vector lane_of as the input.)

**Comment by abrown** [comment]
@bjorn3 thanks for pointing out the issue! I changed the encoding of `scalar_to_vector` for floats to be a null encoding. Doing this, I didn't have to change the instruction types and I no longer see the weird register movement; @bnjbvr, but I can do the last thing you proposed if you think that makes more sense but I'll close this as resolved for now.

**Comment by abrown** [comment]
[Here](https://github.com/abrown/cranelift/compare/add-simd-const-x86-refactored...abrown:improve-extractlane#diff-d8dea7e9b6533024c2c26fbb8d88867bR1698-R1706) is the crux of what changed to get this to work.

**Comment by bnjbvr** [comment]
@abrown I've opened a PR to make this type sane at the IR level, but it wouldn't even have prevented this, since this doesn't happen at the SSA level but at the encodings level.
