### ISSUE TITLE
Calling functions in a host runtime from generated cranelift code

### ISSUE THREAD

**Issue by tomshackell** [CraneStation/cranelift#964]
I've been doing some experiments with cranelift, following along the excellent `simplejit-demo`. However, there's one thing I can't work out how to achieve. I've got a host system (in Rust) generating cranelift IR and loading it dynamically using the `SimpleJITBackend`. I want the generated code to be able to make calls into the Rust host code. I've found that I can declare the functions with `Module::declare_function`, however I can't find any way to tell cranelift what the actual function pointer for that Rust function is. Hence when I try to run it, it complains that the symbol cannot be resolved. I'm essentially looking for the equivalent to LLVM's `ExecutionEngine::addGlobalMapping` function.

I'm sure this must be possible, as this seems essential for using cranelift as an embedded JIT, but I can't find any references describing how I should go about doing so.

Cheers.

**Comment by bjorn3** [comment]
You could use https://docs.rs/cranelift-simplejit/0.41.0/cranelift_simplejit/struct.SimpleJITBuilder.html#method.symbol

**Comment by tomshackell** [comment]
Perfect, thanks.
